/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationAccessibility } from './applicationAccessibility';
import { ApplicationCredentials } from './applicationCredentials';
import { ApplicationLicensing } from './applicationLicensing';
import { ApplicationSettings } from './applicationSettings';
import { ApplicationSignOnMode } from './applicationSignOnMode';
import { ApplicationVisibility } from './applicationVisibility';
export declare class Application {
    '_embedded'?: {
        [key: string]: object;
    };
    '_links'?: {
        [key: string]: object;
    };
    'accessibility'?: ApplicationAccessibility;
    'created'?: Date;
    'credentials'?: ApplicationCredentials;
    'features'?: Array<string>;
    'id'?: string;
    'label'?: string;
    'lastUpdated'?: Date;
    'licensing'?: ApplicationLicensing;
    'name'?: string;
    'profile'?: {
        [key: string]: object;
    };
    'settings'?: ApplicationSettings;
    'signOnMode'?: ApplicationSignOnMode;
    'status'?: Application.StatusEnum;
    'visibility'?: ApplicationVisibility;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace Application {
    enum StatusEnum {
        Active,
        Inactive,
        Deleted
    }
}
