/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorizationServerCredentials } from './authorizationServerCredentials';
export declare class AuthorizationServer {
    '_links'?: {
        [key: string]: object;
    };
    'audiences'?: Array<string>;
    'created'?: Date;
    'credentials'?: AuthorizationServerCredentials;
    'description'?: string;
    'id'?: string;
    'issuer'?: string;
    'issuerMode'?: AuthorizationServer.IssuerModeEnum;
    'lastUpdated'?: Date;
    'name'?: string;
    'status'?: AuthorizationServer.StatusEnum;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace AuthorizationServer {
    enum IssuerModeEnum {
        OrgUrl,
        CustomUrl
    }
    enum StatusEnum {
        Active,
        Inactive
    }
}
