/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogApplicationStatus } from './catalogApplicationStatus';
export declare class CatalogApplication {
    'id'?: string;
    'name'?: string;
    'displayName'?: string;
    'description'?: string;
    'status'?: CatalogApplicationStatus;
    'lastUpdated'?: Date;
    'category'?: string;
    'verificationStatus'?: string;
    'website'?: string;
    'signOnModes'?: Array<string>;
    'features'?: Array<string>;
    '_links'?: {
        [key: string]: object;
    };
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
