/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyAccountLink } from './policyAccountLink';
import { PolicySubject } from './policySubject';
import { Provisioning } from './provisioning';
export declare class IdentityProviderPolicy {
    'accountLink'?: PolicyAccountLink;
    'maxClockSkew'?: number;
    'provisioning'?: Provisioning;
    'subject'?: PolicySubject;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
