/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProviderPolicy } from './identityProviderPolicy';
import { Protocol } from './protocol';
export declare class IdentityProvider {
    '_links'?: {
        [key: string]: object;
    };
    'created'?: Date;
    'id'?: string;
    'issuerMode'?: IdentityProvider.IssuerModeEnum;
    'lastUpdated'?: Date;
    'name'?: string;
    'policy'?: IdentityProviderPolicy;
    'protocol'?: Protocol;
    'status'?: IdentityProvider.StatusEnum;
    'type'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace IdentityProvider {
    enum IssuerModeEnum {
        OrgUrl,
        CustomUrlDomain
    }
    enum StatusEnum {
        Active,
        Inactive
    }
}
