/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class IdentityProviderPolicyRuleCondition {
    'idpIds'?: Array<string>;
    'provider'?: IdentityProviderPolicyRuleCondition.ProviderEnum;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace IdentityProviderPolicyRuleCondition {
    enum ProviderEnum {
        Any,
        Okta,
        SpecificIdp
    }
}
