/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineHookChannel } from './inlineHookChannel';
import { InlineHookStatus } from './inlineHookStatus';
import { InlineHookType } from './inlineHookType';
export declare class InlineHook {
    '_links'?: {
        [key: string]: object;
    };
    'channel'?: InlineHookChannel;
    'created'?: Date;
    'id'?: string;
    'lastUpdated'?: Date;
    'name'?: string;
    'status'?: InlineHookStatus;
    'type'?: InlineHookType;
    'version'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
