/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IonField } from './ionField';
export declare class IonForm {
    'accepts'?: string;
    'href'?: string;
    'method'?: string;
    'name'?: string;
    'produces'?: string;
    'refresh'?: number;
    'rel'?: Array<string>;
    'relatesTo'?: Array<string>;
    'value'?: Array<IonField>;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
