/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class JsonWebKey {
    '_links'?: {
        [key: string]: object;
    };
    'alg'?: string;
    'created'?: Date;
    'e'?: string;
    'expiresAt'?: Date;
    'key_ops'?: Array<string>;
    'kid'?: string;
    'kty'?: string;
    'lastUpdated'?: Date;
    'n'?: string;
    'status'?: string;
    'use'?: string;
    'x5c'?: Array<string>;
    'x5t'?: string;
    'x5t#S256'?: string;
    'x5u'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
