/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogAuthenticationProvider } from './logAuthenticationProvider';
import { LogCredentialProvider } from './logCredentialProvider';
import { LogCredentialType } from './logCredentialType';
import { LogIssuer } from './logIssuer';
export declare class LogAuthenticationContext {
    'authenticationProvider'?: LogAuthenticationProvider;
    'authenticationStep'?: number;
    'credentialProvider'?: LogCredentialProvider;
    'credentialType'?: LogCredentialType;
    'externalSessionId'?: string;
    'interface'?: string;
    'issuer'?: LogIssuer;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
