/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogActor } from './logActor';
import { LogAuthenticationContext } from './logAuthenticationContext';
import { LogClient } from './logClient';
import { LogDebugContext } from './logDebugContext';
import { LogOutcome } from './logOutcome';
import { LogRequest } from './logRequest';
import { LogSecurityContext } from './logSecurityContext';
import { LogSeverity } from './logSeverity';
import { LogTarget } from './logTarget';
import { LogTransaction } from './logTransaction';
export declare class LogEvent {
    'actor'?: LogActor;
    'authenticationContext'?: LogAuthenticationContext;
    'client'?: LogClient;
    'debugContext'?: LogDebugContext;
    'displayMessage'?: string;
    'eventType'?: string;
    'legacyEventType'?: string;
    'outcome'?: LogOutcome;
    'published'?: Date;
    'request'?: LogRequest;
    'securityContext'?: LogSecurityContext;
    'severity'?: LogSeverity;
    'target'?: Array<LogTarget>;
    'transaction'?: LogTransaction;
    'uuid'?: string;
    'version'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
