/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkZoneAddress } from './networkZoneAddress';
import { NetworkZoneLocation } from './networkZoneLocation';
import { NetworkZoneStatus } from './networkZoneStatus';
import { NetworkZoneType } from './networkZoneType';
import { NetworkZoneUsage } from './networkZoneUsage';
export declare class NetworkZone {
    'type'?: NetworkZoneType;
    'id'?: string;
    'name'?: string;
    'system'?: boolean;
    'usage'?: NetworkZoneUsage;
    'status'?: NetworkZoneStatus;
    'proxyType'?: string;
    'locations'?: Array<NetworkZoneLocation>;
    'gateways'?: Array<NetworkZoneAddress>;
    'proxies'?: Array<NetworkZoneAddress>;
    'asns'?: Array<string>;
    'created'?: Date;
    'lastUpdated'?: Date;
    '_links'?: {
        [key: string]: object;
    };
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
