/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyRuleConditions } from './policyRuleConditions';
import { PolicyType } from './policyType';
export declare class Policy {
    '_embedded'?: {
        [key: string]: object;
    };
    '_links'?: {
        [key: string]: object;
    };
    'conditions'?: PolicyRuleConditions;
    'created'?: Date;
    'description'?: string;
    'id'?: string;
    'lastUpdated'?: Date;
    'name'?: string;
    'priority'?: number;
    'status'?: Policy.StatusEnum;
    'system'?: boolean;
    'type'?: PolicyType;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace Policy {
    enum StatusEnum {
        Active,
        Inactive
    }
}
