/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyRuleActions } from './policyRuleActions';
import { PolicyRuleConditions } from './policyRuleConditions';
export declare class PolicyRule {
    'created'?: Date;
    'id'?: string;
    'lastUpdated'?: Date;
    'priority'?: number;
    'status'?: PolicyRule.StatusEnum;
    'system'?: boolean;
    'type'?: PolicyRule.TypeEnum;
    'name'?: string;
    'conditions'?: PolicyRuleConditions;
    'actions'?: PolicyRuleActions;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace PolicyRule {
    enum StatusEnum {
        Active,
        Inactive
    }
    enum TypeEnum {
        SignOn,
        Password
    }
}
