/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProviderCredentials } from './identityProviderCredentials';
import { ProtocolAlgorithms } from './protocolAlgorithms';
import { ProtocolEndpoint } from './protocolEndpoint';
import { ProtocolEndpoints } from './protocolEndpoints';
import { ProtocolRelayState } from './protocolRelayState';
import { ProtocolSettings } from './protocolSettings';
export declare class Protocol {
    'algorithms'?: ProtocolAlgorithms;
    'credentials'?: IdentityProviderCredentials;
    'endpoints'?: ProtocolEndpoints;
    'issuer'?: ProtocolEndpoint;
    'relayState'?: ProtocolRelayState;
    'scopes'?: Array<string>;
    'settings'?: ProtocolSettings;
    'type'?: Protocol.TypeEnum;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace Protocol {
    enum TypeEnum {
        Saml2,
        Oidc,
        Oauth2,
        Mtls
    }
}
