/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProtocolEndpoint } from './protocolEndpoint';
export declare class ProtocolEndpoints {
    'acs'?: ProtocolEndpoint;
    'authorization'?: ProtocolEndpoint;
    'jwks'?: ProtocolEndpoint;
    'metadata'?: ProtocolEndpoint;
    'slo'?: ProtocolEndpoint;
    'sso'?: ProtocolEndpoint;
    'token'?: ProtocolEndpoint;
    'userInfo'?: ProtocolEndpoint;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
