/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class SecurePasswordStoreApplicationSettingsApplication {
    'optionalField1'?: string;
    'optionalField1Value'?: string;
    'optionalField2'?: string;
    'optionalField2Value'?: string;
    'optionalField3'?: string;
    'optionalField3Value'?: string;
    'passwordField'?: string;
    'url'?: string;
    'usernameField'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
