/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCredentials } from './userCredentials';
import { UserProfile } from './userProfile';
import { UserStatus } from './userStatus';
import { UserType } from './userType';
export declare class User {
    '_embedded'?: {
        [key: string]: object;
    };
    '_links'?: {
        [key: string]: object;
    };
    'activated'?: Date;
    'created'?: Date;
    'credentials'?: UserCredentials;
    'id'?: string;
    'lastLogin'?: Date;
    'lastUpdated'?: Date;
    'passwordChanged'?: Date;
    'profile'?: UserProfile;
    'status'?: UserStatus;
    'statusChanged'?: Date;
    'transitioningToStatus'?: UserStatus;
    'type'?: UserType;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
