'use strict';
/* tslint:disable */
/* eslint-disable */
/**
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 2.10.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SchemaApi = exports.SchemaApiFactory = exports.SchemaApiFp = exports.SchemaApiRequestParamCreator = void 0;
// Some imports not used depending on template conditions
// @ts-ignore
const base_1 = require("../base");
const models_1 = require("../models");
const oauth_1 = require("../../oauth");
const http_1 = require("../../http");
const config_loader_1 = require("../../config-loader");
const default_request_executor_1 = require("../../default-request-executor");
const os = require('os');
const packageJson = require('../../../package.json');
const DEFAULT_USER_AGENT = `${packageJson.name}/${packageJson.version} node/${process.versions.node} ${os.platform()}/${os.release()}`;
const repoUrl = 'https://github.com/okta/okta-sdk-nodejs';
const models_2 = require("../models");

/**
 * SchemaApi - request parameter creator
 * @export
 */
const SchemaApiRequestParamCreator = function (configuration) {
    const configLoader = new config_loader_1.ConfigLoader();
    const clientConfig = Object.assign({}, configuration);
    configLoader.applyDefaults();
    configLoader.apply({
        client: clientConfig || {}
    });
    const parsedConfig = configLoader.config;
    const requestExecutor = clientConfig.requestExecutor || new default_request_executor_1.DefaultRequestExecutor();
    const errors = [];
    if (!parsedConfig.client.orgUrl) {
        errors.push('Okta Org URL not provided');
    }
    if (!parsedConfig.client.token && parsedConfig.client.authorizationMode !== 'PrivateKey') {
        errors.push('Okta API token not provided');
    }
    if (parsedConfig.client.authorizationMode === 'PrivateKey') {
        if (!parsedConfig.client.clientId) {
            errors.push('Okta Client ID not provided');
        }
        if (!parsedConfig.client.scopes) {
            errors.push('Scopes not provided');
        }
        if (!parsedConfig.client.privateKey) {
            errors.push('Private Key not provided');
        }
    }
    else if (parsedConfig.client.authorizationMode !== 'SSWS') {
        errors.push('Unknown Authorization Mode');
    }
    if (errors.length) {
        throw new Error(`Found ${errors.length} errors:\n${errors.join('\n')}\nSee ${repoUrl} for usage.`);
    }
    const authorizationMode = parsedConfig.client.authorizationMode;
    const baseUrl = parsedConfig.client.orgUrl.replace(/\/$/, '');
    const apiToken = parsedConfig.client.token;
    let clientId;
    let scopes;
    let privateKey;
    let oauth;
    if (authorizationMode === 'PrivateKey') {
        clientId = parsedConfig.client.clientId;
        scopes = parsedConfig.client.scopes.split(' ');
        privateKey = parsedConfig.client.privateKey;
        oauth = new oauth_1.OAuth(this);
    }
    const http = new http_1.Http({
        cacheStore: clientConfig.cacheStore,
        cacheMiddleware: clientConfig.cacheMiddleware,
        defaultCacheMiddlewareResponseBufferSize: clientConfig.defaultCacheMiddlewareResponseBufferSize,
        requestExecutor: requestExecutor,
        oauth: oauth
    });
    if (authorizationMode === 'SSWS') {
        http.defaultHeaders.Authorization = `SSWS ${apiToken}`;
    }
    http.defaultHeaders['User-Agent'] = parsedConfig.client.userAgent ? parsedConfig.client.userAgent + ' ' + DEFAULT_USER_AGENT : DEFAULT_USER_AGENT;
    return {
        http,
        /**
          * Fetches the Schema for an App User
          * @summary Fetches the Schema for an App User
          * @param {string} appInstanceId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getApplicationUserSchema: (appInstanceId, options = {}) => {
            // verify required parameter 'appInstanceId' is not null or undefined
            if (appInstanceId === null || appInstanceId === undefined) {
                throw new base_1.RequiredError('appInstanceId', 'Required parameter appInstanceId was null or undefined when calling getApplicationUserSchema.');
            }
            const localVarPath = `/api/v1/meta/schemas/apps/{appInstanceId}/default`
                .replace(`{${"appInstanceId"}}`, encodeURIComponent(String(appInstanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
          * Fetches the group schema
          * @summary Fetches the group schema
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getGroupSchema: (options = {}) => {
            const localVarPath = `/api/v1/meta/schemas/group/default`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
          * Fetches the schema for a Schema Id.
          * @summary Fetches the schema for a Schema Id.
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getUserSchema: (schemaId, options = {}) => {
            // verify required parameter 'schemaId' is not null or undefined
            if (schemaId === null || schemaId === undefined) {
                throw new base_1.RequiredError('schemaId', 'Required parameter schemaId was null or undefined when calling getUserSchema.');
            }
            const localVarPath = `/api/v1/meta/schemas/user/{schemaId}`
                .replace(`{${"schemaId"}}`, encodeURIComponent(String(schemaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
          * Partial updates on the User Profile properties of the Application User Schema.
          * @summary Partial updates on the User Profile properties of the Application User Schema.
          * @param {string} appInstanceId
          * @param {UserSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateApplicationUserProfile: (appInstanceId, body, options = {}) => {
            // verify required parameter 'appInstanceId' is not null or undefined
            if (appInstanceId === null || appInstanceId === undefined) {
                throw new base_1.RequiredError('appInstanceId', 'Required parameter appInstanceId was null or undefined when calling updateApplicationUserProfile.');
            }
            const localVarPath = `/api/v1/meta/schemas/apps/{appInstanceId}/default`
                .replace(`{${"appInstanceId"}}`, encodeURIComponent(String(appInstanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
          * Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @summary Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @param {GroupSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateGroupSchema: (body, options = {}) => {
            const localVarPath = `/api/v1/meta/schemas/group/default`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
          * Partial updates on the User Profile properties of the user schema.
          * @summary Update User Profile
          * @param {UserSchema} body
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateUserProfile: (body, schemaId, options = {}) => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new base_1.RequiredError('body', 'Required parameter body was null or undefined when calling updateUserProfile.');
            }
            // verify required parameter 'schemaId' is not null or undefined
            if (schemaId === null || schemaId === undefined) {
                throw new base_1.RequiredError('schemaId', 'Required parameter schemaId was null or undefined when calling updateUserProfile.');
            }
            const localVarPath = `/api/v1/meta/schemas/user/{schemaId}`
                .replace(`{${"schemaId"}}`, encodeURIComponent(String(schemaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication api_token required
            if (configuration && configuration.apiToken) {
                const localVarApiKeyValue = typeof configuration.apiToken === 'function'
                    ? configuration.apiToken("Authorization")
                    : configuration.apiToken;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }
            // authentication oauth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("oauth2", ["okta.apps.read", "okta.apps.manage", "okta.authenticators.read", "okta.authenticators.manage", "okta.authorizationServers.read", "okta.authorizationServers.manage", "okta.brands.read", "okta.brands.manage", "okta.captchas.manage", "okta.captchas.read", "okta.domains.read", "okta.domains.manage", "okta.eventHooks.read", "okta.eventHooks.manage", "okta.groups.read", "okta.groups.manage", "okta.roles.read", "okta.roles.manage", "okta.idps.read", "okta.idps.manage", "okta.users.manage", "okta.inlineHooks.read", "okta.inlineHooks.manage", "okta.logs.read", "okta.profileMappings.read", "okta.profileMappings.manage", "okta.schemas.read", "okta.schemas.manage", "okta.linkedObjects.read", "okta.linkedObjects.manage", "okta.userTypes.read", "okta.userTypes.manage", "okta.orgs.read", "okta.orgs.manage", "okta.policies.read", "okta.policies.manage", "okta.sessions.read", "okta.sessions.manage", "okta.templates.read", "okta.templates.manage", "okta.trustedOrigins.read", "okta.trustedOrigins.manage", "okta.users.read.self", "okta.users.read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    };
};
exports.SchemaApiRequestParamCreator = SchemaApiRequestParamCreator;
/**
 * SchemaApi - functional programming interface
 * @export
 */
const SchemaApiFp = function (configuration) {
    return {
        /**
          * Fetches the Schema for an App User
          * @summary Fetches the Schema for an App User
          * @param {string} appInstanceId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getApplicationUserSchema(appInstanceId, options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.getApplicationUserSchema(appInstanceId, options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_2.UserSchema(data)));
            };
        },
        /**
          * Fetches the group schema
          * @summary Fetches the group schema
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getGroupSchema(options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.getGroupSchema(options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_1.GroupSchema(data)));
            };
        },
        /**
          * Fetches the schema for a Schema Id.
          * @summary Fetches the schema for a Schema Id.
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getUserSchema(schemaId, options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.getUserSchema(schemaId, options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_2.UserSchema(data)));
            };
        },
        /**
          * Partial updates on the User Profile properties of the Application User Schema.
          * @summary Partial updates on the User Profile properties of the Application User Schema.
          * @param {string} appInstanceId
          * @param {UserSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateApplicationUserProfile(appInstanceId, body, options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.updateApplicationUserProfile(appInstanceId, body, options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_2.UserSchema(data)));
            };
        },
        /**
          * Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @summary Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @param {GroupSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateGroupSchema(body, options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.updateGroupSchema(body, options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_1.GroupSchema(data)));
            };
        },
        /**
          * Partial updates on the User Profile properties of the user schema.
          * @summary Update User Profile
          * @param {UserSchema} body
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateUserProfile(body, schemaId, options) {
            const api = exports.SchemaApiRequestParamCreator(configuration);
            const localVarRequestArgs = api.updateUserProfile(body, schemaId, options);
            return (http = api.http, basePath = configuration.basePath || configuration.orgUrl) => {
                const requestArgs = { ...localVarRequestArgs.options, url: basePath + localVarRequestArgs.url };
                return http.http(requestArgs.url, requestArgs).then(res => res.json().then(data => new models_2.UserSchema(data)));
            };
        },
    };
};
exports.SchemaApiFp = SchemaApiFp;
/**
 * SchemaApi - factory interface
 * @export
 */
const SchemaApiFactory = function (configuration, basePath, http) {
    return {
        /**
          * Fetches the Schema for an App User
          * @summary Fetches the Schema for an App User
          * @param {string} appInstanceId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getApplicationUserSchema(appInstanceId, options) {
            return exports.SchemaApiFp(configuration).getApplicationUserSchema(appInstanceId, options)(http, basePath);
        },
        /**
          * Fetches the group schema
          * @summary Fetches the group schema
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getGroupSchema(options) {
            return exports.SchemaApiFp(configuration).getGroupSchema(options)(http, basePath);
        },
        /**
          * Fetches the schema for a Schema Id.
          * @summary Fetches the schema for a Schema Id.
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        getUserSchema(schemaId, options) {
            return exports.SchemaApiFp(configuration).getUserSchema(schemaId, options)(http, basePath);
        },
        /**
          * Partial updates on the User Profile properties of the Application User Schema.
          * @summary Partial updates on the User Profile properties of the Application User Schema.
          * @param {string} appInstanceId
          * @param {UserSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateApplicationUserProfile(appInstanceId, body, options) {
            return exports.SchemaApiFp(configuration).updateApplicationUserProfile(appInstanceId, body, options)(http, basePath);
        },
        /**
          * Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @summary Updates, adds ore removes one or more custom Group Profile properties in the schema
          * @param {GroupSchema} [body]
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateGroupSchema(body, options) {
            return exports.SchemaApiFp(configuration).updateGroupSchema(body, options)(http, basePath);
        },
        /**
          * Partial updates on the User Profile properties of the user schema.
          * @summary Update User Profile
          * @param {UserSchema} body
          * @param {string} schemaId
          * @param {*} [options] Override http request option.
          * @throws {RequiredError}
          */
        updateUserProfile(body, schemaId, options) {
            return exports.SchemaApiFp(configuration).updateUserProfile(body, schemaId, options)(http, basePath);
        },
    };
};
exports.SchemaApiFactory = SchemaApiFactory;
/**
 * SchemaApi - object-oriented interface
 * @export
 * @class SchemaApi
 * @extends {BaseAPI}
 */
class SchemaApi extends base_1.BaseAPI {
    /**
      * Fetches the Schema for an App User
      * @summary Fetches the Schema for an App User
      * @param {string} appInstanceId
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    getApplicationUserSchema(appInstanceId, options) {
        return exports.SchemaApiFp(this.configuration).getApplicationUserSchema(appInstanceId, options)(this.httpClient, this.basePath);
    }
    /**
      * Fetches the group schema
      * @summary Fetches the group schema
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    getGroupSchema(options) {
        return exports.SchemaApiFp(this.configuration).getGroupSchema(options)(this.httpClient, this.basePath);
    }
    /**
      * Fetches the schema for a Schema Id.
      * @summary Fetches the schema for a Schema Id.
      * @param {string} schemaId
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    getUserSchema(schemaId, options) {
        return exports.SchemaApiFp(this.configuration).getUserSchema(schemaId, options)(this.httpClient, this.basePath);
    }
    /**
      * Partial updates on the User Profile properties of the Application User Schema.
      * @summary Partial updates on the User Profile properties of the Application User Schema.
      * @param {string} appInstanceId
      * @param {UserSchema} [body]
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    updateApplicationUserProfile(appInstanceId, body, options) {
        return exports.SchemaApiFp(this.configuration).updateApplicationUserProfile(appInstanceId, body, options)(this.httpClient, this.basePath);
    }
    /**
      * Updates, adds ore removes one or more custom Group Profile properties in the schema
      * @summary Updates, adds ore removes one or more custom Group Profile properties in the schema
      * @param {GroupSchema} [body]
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    updateGroupSchema(body, options) {
        return exports.SchemaApiFp(this.configuration).updateGroupSchema(body, options)(this.httpClient, this.basePath);
    }
    /**
      * Partial updates on the User Profile properties of the user schema.
      * @summary Update User Profile
      * @param {UserSchema} body
      * @param {string} schemaId
      * @param {*} [options] Override http request option.
      * @throws {RequiredError}
      * @memberof SchemaApi
      */
    updateUserProfile(body, schemaId, options) {
        return exports.SchemaApiFp(this.configuration).updateUserProfile(body, schemaId, options)(this.httpClient, this.basePath);
    }
}
exports.SchemaApi = SchemaApi;
