/**
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 2.10.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserSchemaAttribute } from './user-schema-attribute';
/**
 *
 * @export
 * @class UserSchemaBaseProperties
 */
export declare class UserSchemaBaseProperties {
  constructor(resourceJson: Record<string, unknown>);
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  login?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  firstName?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  lastName?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  middleName?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  honorificPrefix?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  honorificSuffix?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  email?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  title?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  displayName?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  nickName?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  profileUrl?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  secondEmail?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  mobilePhone?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  primaryPhone?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  streetAddress?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  city?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  state?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  zipCode?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  countryCode?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  postalAddress?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  preferredLanguage?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  locale?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  timezone?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  userType?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  employeeNumber?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  costCenter?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  organization?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  division?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  department?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  managerId?: UserSchemaAttribute;
  /**
      *
      * @type {UserSchemaAttribute}
      * @memberof UserSchemaBaseProperties
      */
  manager?: UserSchemaAttribute;
}
