"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActivateFactorRequest = void 0;
var ActivateFactorRequest = /** @class */ (function () {
    function ActivateFactorRequest() {
    }
    ActivateFactorRequest.getAttributeTypeMap = function () {
        return ActivateFactorRequest.attributeTypeMap;
    };
    ActivateFactorRequest.discriminator = undefined;
    ActivateFactorRequest.attributeTypeMap = [
        {
            "name": "attestation",
            "baseName": "attestation",
            "type": "string"
        },
        {
            "name": "clientData",
            "baseName": "clientData",
            "type": "string"
        },
        {
            "name": "passCode",
            "baseName": "passCode",
            "type": "string"
        },
        {
            "name": "registrationData",
            "baseName": "registrationData",
            "type": "string"
        },
        {
            "name": "stateToken",
            "baseName": "stateToken",
            "type": "string"
        }
    ];
    return ActivateFactorRequest;
}());
exports.ActivateFactorRequest = ActivateFactorRequest;
