/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { AppAndInstanceConditionEvaluatorAppOrInstance } from './appAndInstanceConditionEvaluatorAppOrInstance';

export class AppAndInstancePolicyRuleCondition {
    'exclude'?: Array<AppAndInstanceConditionEvaluatorAppOrInstance>;
    'include'?: Array<AppAndInstanceConditionEvaluatorAppOrInstance>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Array<AppAndInstanceConditionEvaluatorAppOrInstance>"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<AppAndInstanceConditionEvaluatorAppOrInstance>"
        }    ];

    static getAttributeTypeMap() {
        return AppAndInstancePolicyRuleCondition.attributeTypeMap;
    }
}

