"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicationSettingsNotificationsVpn = void 0;
var ApplicationSettingsNotificationsVpn = /** @class */ (function () {
    function ApplicationSettingsNotificationsVpn() {
    }
    ApplicationSettingsNotificationsVpn.getAttributeTypeMap = function () {
        return ApplicationSettingsNotificationsVpn.attributeTypeMap;
    };
    ApplicationSettingsNotificationsVpn.discriminator = undefined;
    ApplicationSettingsNotificationsVpn.attributeTypeMap = [
        {
            "name": "helpUrl",
            "baseName": "helpUrl",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "ApplicationSettingsNotificationsVpnNetwork"
        }
    ];
    return ApplicationSettingsNotificationsVpn;
}());
exports.ApplicationSettingsNotificationsVpn = ApplicationSettingsNotificationsVpn;
