/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export enum ApplicationSignOnMode {
    Bookmark = <any> 'BOOKMARK',
    BasicAuth = <any> 'BASIC_AUTH',
    BrowserPlugin = <any> 'BROWSER_PLUGIN',
    SecurePasswordStore = <any> 'SECURE_PASSWORD_STORE',
    AutoLogin = <any> 'AUTO_LOGIN',
    WsFederation = <any> 'WS_FEDERATION',
    Saml20 = <any> 'SAML_2_0',
    OpenidConnect = <any> 'OPENID_CONNECT',
    Saml11 = <any> 'SAML_1_1'
}
