"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicationSettingsNotes = void 0;
var ApplicationSettingsNotes = /** @class */ (function () {
    function ApplicationSettingsNotes() {
    }
    ApplicationSettingsNotes.getAttributeTypeMap = function () {
        return ApplicationSettingsNotes.attributeTypeMap;
    };
    ApplicationSettingsNotes.discriminator = undefined;
    ApplicationSettingsNotes.attributeTypeMap = [
        {
            "name": "admin",
            "baseName": "admin",
            "type": "string"
        },
        {
            "name": "enduser",
            "baseName": "enduser",
            "type": "string"
        }
    ];
    return ApplicationSettingsNotes;
}());
exports.ApplicationSettingsNotes = ApplicationSettingsNotes;
