/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { ApplicationSettingsNotificationsVpnNetwork } from './applicationSettingsNotificationsVpnNetwork';

export class ApplicationSettingsNotificationsVpn {
    'helpUrl'?: string;
    'message'?: string;
    'network'?: ApplicationSettingsNotificationsVpnNetwork;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "helpUrl",
            "baseName": "helpUrl",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "ApplicationSettingsNotificationsVpnNetwork"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationSettingsNotificationsVpn.attributeTypeMap;
    }
}

