"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicationSettingsNotificationsVpnNetwork = void 0;
var ApplicationSettingsNotificationsVpnNetwork = /** @class */ (function () {
    function ApplicationSettingsNotificationsVpnNetwork() {
    }
    ApplicationSettingsNotificationsVpnNetwork.getAttributeTypeMap = function () {
        return ApplicationSettingsNotificationsVpnNetwork.attributeTypeMap;
    };
    ApplicationSettingsNotificationsVpnNetwork.discriminator = undefined;
    ApplicationSettingsNotificationsVpnNetwork.attributeTypeMap = [
        {
            "name": "connection",
            "baseName": "connection",
            "type": "string"
        },
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Array<string>"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }
    ];
    return ApplicationSettingsNotificationsVpnNetwork;
}());
exports.ApplicationSettingsNotificationsVpnNetwork = ApplicationSettingsNotificationsVpnNetwork;
