"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicationCredentials = void 0;
var ApplicationCredentials = /** @class */ (function () {
    function ApplicationCredentials() {
    }
    ApplicationCredentials.getAttributeTypeMap = function () {
        return ApplicationCredentials.attributeTypeMap;
    };
    ApplicationCredentials.discriminator = undefined;
    ApplicationCredentials.attributeTypeMap = [
        {
            "name": "signing",
            "baseName": "signing",
            "type": "ApplicationCredentialsSigning"
        },
        {
            "name": "userNameTemplate",
            "baseName": "userNameTemplate",
            "type": "ApplicationCredentialsUsernameTemplate"
        }
    ];
    return ApplicationCredentials;
}());
exports.ApplicationCredentials = ApplicationCredentials;
