"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssignRoleRequest = void 0;
var AssignRoleRequest = /** @class */ (function () {
    function AssignRoleRequest() {
    }
    AssignRoleRequest.getAttributeTypeMap = function () {
        return AssignRoleRequest.attributeTypeMap;
    };
    AssignRoleRequest.discriminator = undefined;
    AssignRoleRequest.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "RoleType"
        }
    ];
    return AssignRoleRequest;
}());
exports.AssignRoleRequest = AssignRoleRequest;
