"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticationProvider = void 0;
var AuthenticationProvider = /** @class */ (function () {
    function AuthenticationProvider() {
    }
    AuthenticationProvider.getAttributeTypeMap = function () {
        return AuthenticationProvider.attributeTypeMap;
    };
    AuthenticationProvider.discriminator = undefined;
    AuthenticationProvider.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AuthenticationProviderType"
        }
    ];
    return AuthenticationProvider;
}());
exports.AuthenticationProvider = AuthenticationProvider;
