"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthorizationServerPolicyRuleActions = void 0;
var AuthorizationServerPolicyRuleActions = /** @class */ (function () {
    function AuthorizationServerPolicyRuleActions() {
    }
    AuthorizationServerPolicyRuleActions.getAttributeTypeMap = function () {
        return AuthorizationServerPolicyRuleActions.attributeTypeMap;
    };
    AuthorizationServerPolicyRuleActions.discriminator = undefined;
    AuthorizationServerPolicyRuleActions.attributeTypeMap = [
        {
            "name": "token",
            "baseName": "token",
            "type": "TokenAuthorizationServerPolicyRuleAction"
        }
    ];
    return AuthorizationServerPolicyRuleActions;
}());
exports.AuthorizationServerPolicyRuleActions = AuthorizationServerPolicyRuleActions;
