/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthenticatorSettings } from './authenticatorSettings';
import { AuthenticatorStatus } from './authenticatorStatus';
import { AuthenticatorType } from './authenticatorType';

export class Authenticator {
    '_links'?: { [key: string]: object; };
    'created'?: Date;
    'id'?: string;
    'key'?: string;
    'status'?: AuthenticatorStatus;
    'lastUpdated'?: Date;
    'name'?: string;
    'type'?: AuthenticatorType;
    'settings'?: AuthenticatorSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AuthenticatorStatus"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AuthenticatorType"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "AuthenticatorSettings"
        }    ];

    static getAttributeTypeMap() {
        return Authenticator.attributeTypeMap;
    }
}

