"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Authenticator = void 0;
var Authenticator = /** @class */ (function () {
    function Authenticator() {
    }
    Authenticator.getAttributeTypeMap = function () {
        return Authenticator.attributeTypeMap;
    };
    Authenticator.discriminator = undefined;
    Authenticator.attributeTypeMap = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AuthenticatorStatus"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AuthenticatorType"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "AuthenticatorSettings"
        }
    ];
    return Authenticator;
}());
exports.Authenticator = Authenticator;
