"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoLoginApplicationSettings = void 0;
var AutoLoginApplicationSettings = /** @class */ (function () {
    function AutoLoginApplicationSettings() {
    }
    AutoLoginApplicationSettings.getAttributeTypeMap = function () {
        return AutoLoginApplicationSettings.attributeTypeMap;
    };
    AutoLoginApplicationSettings.discriminator = undefined;
    AutoLoginApplicationSettings.attributeTypeMap = [
        {
            "name": "signOn",
            "baseName": "signOn",
            "type": "AutoLoginApplicationSettingsSignOn"
        }
    ];
    return AutoLoginApplicationSettings;
}());
exports.AutoLoginApplicationSettings = AutoLoginApplicationSettings;
