"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BasicAuthApplication = void 0;
var BasicAuthApplication = /** @class */ (function () {
    function BasicAuthApplication() {
    }
    BasicAuthApplication.getAttributeTypeMap = function () {
        return BasicAuthApplication.attributeTypeMap;
    };
    BasicAuthApplication.discriminator = undefined;
    BasicAuthApplication.attributeTypeMap = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "SchemeApplicationCredentials"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "BasicApplicationSettings"
        }
    ];
    return BasicAuthApplication;
}());
exports.BasicAuthApplication = BasicAuthApplication;
