"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookmarkApplicationSettingsApplication = void 0;
var BookmarkApplicationSettingsApplication = /** @class */ (function () {
    function BookmarkApplicationSettingsApplication() {
    }
    BookmarkApplicationSettingsApplication.getAttributeTypeMap = function () {
        return BookmarkApplicationSettingsApplication.attributeTypeMap;
    };
    BookmarkApplicationSettingsApplication.discriminator = undefined;
    BookmarkApplicationSettingsApplication.attributeTypeMap = [
        {
            "name": "requestIntegration",
            "baseName": "requestIntegration",
            "type": "boolean"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }
    ];
    return BookmarkApplicationSettingsApplication;
}());
exports.BookmarkApplicationSettingsApplication = BookmarkApplicationSettingsApplication;
