"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CAPTCHAInstance = void 0;
var CAPTCHAInstance = /** @class */ (function () {
    function CAPTCHAInstance() {
    }
    CAPTCHAInstance.getAttributeTypeMap = function () {
        return CAPTCHAInstance.attributeTypeMap;
    };
    CAPTCHAInstance.discriminator = undefined;
    CAPTCHAInstance.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "secretKey",
            "baseName": "secretKey",
            "type": "string"
        },
        {
            "name": "siteKey",
            "baseName": "siteKey",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CAPTCHAInstance.TypeEnum"
        },
        {
            "name": "link",
            "baseName": "_link",
            "type": "CAPTCHAInstanceLink"
        }
    ];
    return CAPTCHAInstance;
}());
exports.CAPTCHAInstance = CAPTCHAInstance;
(function (CAPTCHAInstance) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Hcaptcha"] = 'HCAPTCHA'] = "Hcaptcha";
        TypeEnum[TypeEnum["RecaptchaV2"] = 'RECAPTCHA_V2'] = "RecaptchaV2";
    })(TypeEnum = CAPTCHAInstance.TypeEnum || (CAPTCHAInstance.TypeEnum = {}));
})(CAPTCHAInstance = exports.CAPTCHAInstance || (exports.CAPTCHAInstance = {}));
exports.CAPTCHAInstance = CAPTCHAInstance;
