"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChangePasswordRequest = void 0;
var ChangePasswordRequest = /** @class */ (function () {
    function ChangePasswordRequest() {
    }
    ChangePasswordRequest.getAttributeTypeMap = function () {
        return ChangePasswordRequest.attributeTypeMap;
    };
    ChangePasswordRequest.discriminator = undefined;
    ChangePasswordRequest.attributeTypeMap = [
        {
            "name": "newPassword",
            "baseName": "newPassword",
            "type": "PasswordCredential"
        },
        {
            "name": "oldPassword",
            "baseName": "oldPassword",
            "type": "PasswordCredential"
        }
    ];
    return ChangePasswordRequest;
}());
exports.ChangePasswordRequest = ChangePasswordRequest;
