"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientPolicyCondition = void 0;
var ClientPolicyCondition = /** @class */ (function () {
    function ClientPolicyCondition() {
    }
    ClientPolicyCondition.getAttributeTypeMap = function () {
        return ClientPolicyCondition.attributeTypeMap;
    };
    ClientPolicyCondition.discriminator = undefined;
    ClientPolicyCondition.attributeTypeMap = [
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }
    ];
    return ClientPolicyCondition;
}());
exports.ClientPolicyCondition = ClientPolicyCondition;
