/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { UserCredentials } from './userCredentials';
import { UserProfile } from './userProfile';
import { UserType } from './userType';

export class CreateUserRequest {
    'credentials'?: UserCredentials;
    'groupIds'?: Array<string>;
    'profile'?: UserProfile;
    'type'?: UserType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "UserCredentials"
        },
        {
            "name": "groupIds",
            "baseName": "groupIds",
            "type": "Array<string>"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "UserProfile"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UserType"
        }    ];

    static getAttributeTypeMap() {
        return CreateUserRequest.attributeTypeMap;
    }
}

