"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateSessionRequest = void 0;
var CreateSessionRequest = /** @class */ (function () {
    function CreateSessionRequest() {
    }
    CreateSessionRequest.getAttributeTypeMap = function () {
        return CreateSessionRequest.attributeTypeMap;
    };
    CreateSessionRequest.discriminator = undefined;
    CreateSessionRequest.attributeTypeMap = [
        {
            "name": "sessionToken",
            "baseName": "sessionToken",
            "type": "string"
        }
    ];
    return CreateSessionRequest;
}());
exports.CreateSessionRequest = CreateSessionRequest;
