"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateUserRequest = void 0;
var CreateUserRequest = /** @class */ (function () {
    function CreateUserRequest() {
    }
    CreateUserRequest.getAttributeTypeMap = function () {
        return CreateUserRequest.attributeTypeMap;
    };
    CreateUserRequest.discriminator = undefined;
    CreateUserRequest.attributeTypeMap = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "UserCredentials"
        },
        {
            "name": "groupIds",
            "baseName": "groupIds",
            "type": "Array<string>"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "UserProfile"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UserType"
        }
    ];
    return CreateUserRequest;
}());
exports.CreateUserRequest = CreateUserRequest;
