/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CsrMetadataSubject {
    'commonName'?: string;
    'countryName'?: string;
    'localityName'?: string;
    'organizationName'?: string;
    'organizationalUnitName'?: string;
    'stateOrProvinceName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commonName",
            "baseName": "commonName",
            "type": "string"
        },
        {
            "name": "countryName",
            "baseName": "countryName",
            "type": "string"
        },
        {
            "name": "localityName",
            "baseName": "localityName",
            "type": "string"
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string"
        },
        {
            "name": "organizationalUnitName",
            "baseName": "organizationalUnitName",
            "type": "string"
        },
        {
            "name": "stateOrProvinceName",
            "baseName": "stateOrProvinceName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CsrMetadataSubject.attributeTypeMap;
    }
}

