"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CsrMetadataSubject = void 0;
var CsrMetadataSubject = /** @class */ (function () {
    function CsrMetadataSubject() {
    }
    CsrMetadataSubject.getAttributeTypeMap = function () {
        return CsrMetadataSubject.attributeTypeMap;
    };
    CsrMetadataSubject.discriminator = undefined;
    CsrMetadataSubject.attributeTypeMap = [
        {
            "name": "commonName",
            "baseName": "commonName",
            "type": "string"
        },
        {
            "name": "countryName",
            "baseName": "countryName",
            "type": "string"
        },
        {
            "name": "localityName",
            "baseName": "localityName",
            "type": "string"
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string"
        },
        {
            "name": "organizationalUnitName",
            "baseName": "organizationalUnitName",
            "type": "string"
        },
        {
            "name": "stateOrProvinceName",
            "baseName": "stateOrProvinceName",
            "type": "string"
        }
    ];
    return CsrMetadataSubject;
}());
exports.CsrMetadataSubject = CsrMetadataSubject;
