"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomHotpUserFactorProfile = void 0;
var CustomHotpUserFactorProfile = /** @class */ (function () {
    function CustomHotpUserFactorProfile() {
    }
    CustomHotpUserFactorProfile.getAttributeTypeMap = function () {
        return CustomHotpUserFactorProfile.attributeTypeMap;
    };
    CustomHotpUserFactorProfile.discriminator = undefined;
    CustomHotpUserFactorProfile.attributeTypeMap = [
        {
            "name": "sharedSecret",
            "baseName": "sharedSecret",
            "type": "string"
        }
    ];
    return CustomHotpUserFactorProfile;
}());
exports.CustomHotpUserFactorProfile = CustomHotpUserFactorProfile;
