"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomHotpUserFactor = void 0;
var CustomHotpUserFactor = /** @class */ (function () {
    function CustomHotpUserFactor() {
    }
    CustomHotpUserFactor.getAttributeTypeMap = function () {
        return CustomHotpUserFactor.attributeTypeMap;
    };
    CustomHotpUserFactor.discriminator = undefined;
    CustomHotpUserFactor.attributeTypeMap = [
        {
            "name": "factorProfileId",
            "baseName": "factorProfileId",
            "type": "string"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "CustomHotpUserFactorProfile"
        }
    ];
    return CustomHotpUserFactor;
}());
exports.CustomHotpUserFactor = CustomHotpUserFactor;
