"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Domain = void 0;
var Domain = /** @class */ (function () {
    function Domain() {
    }
    Domain.getAttributeTypeMap = function () {
        return Domain.attributeTypeMap;
    };
    Domain.discriminator = undefined;
    Domain.attributeTypeMap = [
        {
            "name": "certificateSourceType",
            "baseName": "certificateSourceType",
            "type": "DomainCertificateSourceType"
        },
        {
            "name": "dnsRecords",
            "baseName": "dnsRecords",
            "type": "Array<DNSRecord>"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "publicCertificate",
            "baseName": "publicCertificate",
            "type": "DomainCertificateMetadata"
        },
        {
            "name": "validationStatus",
            "baseName": "validationStatus",
            "type": "DomainValidationStatus"
        }
    ];
    return Domain;
}());
exports.Domain = Domain;
