"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DomainLinks = void 0;
var DomainLinks = /** @class */ (function () {
    function DomainLinks() {
    }
    DomainLinks.getAttributeTypeMap = function () {
        return DomainLinks.attributeTypeMap;
    };
    DomainLinks.discriminator = undefined;
    DomainLinks.attributeTypeMap = [
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "object"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "object"
        },
        {
            "name": "verify",
            "baseName": "verify",
            "type": "object"
        }
    ];
    return DomainLinks;
}());
exports.DomainLinks = DomainLinks;
