"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DomainCertificate = void 0;
var DomainCertificate = /** @class */ (function () {
    function DomainCertificate() {
    }
    DomainCertificate.getAttributeTypeMap = function () {
        return DomainCertificate.attributeTypeMap;
    };
    DomainCertificate.discriminator = undefined;
    DomainCertificate.attributeTypeMap = [
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "string"
        },
        {
            "name": "certificateChain",
            "baseName": "certificateChain",
            "type": "string"
        },
        {
            "name": "privateKey",
            "baseName": "privateKey",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DomainCertificateType"
        }
    ];
    return DomainCertificate;
}());
exports.DomainCertificate = DomainCertificate;
