"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Duration = void 0;
var Duration = /** @class */ (function () {
    function Duration() {
    }
    Duration.getAttributeTypeMap = function () {
        return Duration.attributeTypeMap;
    };
    Duration.discriminator = undefined;
    Duration.attributeTypeMap = [
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }
    ];
    return Duration;
}());
exports.Duration = Duration;
