"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorErrorCauses = void 0;
var ErrorErrorCauses = /** @class */ (function () {
    function ErrorErrorCauses() {
    }
    ErrorErrorCauses.getAttributeTypeMap = function () {
        return ErrorErrorCauses.attributeTypeMap;
    };
    ErrorErrorCauses.discriminator = undefined;
    ErrorErrorCauses.attributeTypeMap = [
        {
            "name": "errorSummary",
            "baseName": "errorSummary",
            "type": "string"
        }
    ];
    return ErrorErrorCauses;
}());
exports.ErrorErrorCauses = ErrorErrorCauses;
