/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export class EventSubscriptions {
    'items'?: Array<string>;
    'type'?: EventSubscriptions.TypeEnum;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<string>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "EventSubscriptions.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return EventSubscriptions.attributeTypeMap;
    }
}

export namespace EventSubscriptions {
    export enum TypeEnum {
        EventType = <any> 'EVENT_TYPE',
        FlowEvent = <any> 'FLOW_EVENT'
    }
}
