"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventHookChannelConfigAuthScheme = void 0;
var EventHookChannelConfigAuthScheme = /** @class */ (function () {
    function EventHookChannelConfigAuthScheme() {
    }
    EventHookChannelConfigAuthScheme.getAttributeTypeMap = function () {
        return EventHookChannelConfigAuthScheme.attributeTypeMap;
    };
    EventHookChannelConfigAuthScheme.discriminator = undefined;
    EventHookChannelConfigAuthScheme.attributeTypeMap = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "EventHookChannelConfigAuthSchemeType"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return EventHookChannelConfigAuthScheme;
}());
exports.EventHookChannelConfigAuthScheme = EventHookChannelConfigAuthScheme;
