"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventHookChannelConfigHeader = void 0;
var EventHookChannelConfigHeader = /** @class */ (function () {
    function EventHookChannelConfigHeader() {
    }
    EventHookChannelConfigHeader.getAttributeTypeMap = function () {
        return EventHookChannelConfigHeader.attributeTypeMap;
    };
    EventHookChannelConfigHeader.discriminator = undefined;
    EventHookChannelConfigHeader.attributeTypeMap = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return EventHookChannelConfigHeader;
}());
exports.EventHookChannelConfigHeader = EventHookChannelConfigHeader;
