/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum FactorResultType {
    Success = <any> 'SUCCESS',
    Challenge = <any> 'CHALLENGE',
    Waiting = <any> 'WAITING',
    Failed = <any> 'FAILED',
    Rejected = <any> 'REJECTED',
    Timeout = <any> 'TIMEOUT',
    TimeWindowExceeded = <any> 'TIME_WINDOW_EXCEEDED',
    PasscodeReplayed = <any> 'PASSCODE_REPLAYED',
    Error = <any> 'ERROR',
    Cancelled = <any> 'CANCELLED'
}
