"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Feature = void 0;
var Feature = /** @class */ (function () {
    function Feature() {
    }
    Feature.getAttributeTypeMap = function () {
        return Feature.attributeTypeMap;
    };
    Feature.discriminator = undefined;
    Feature.attributeTypeMap = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "FeatureStage"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EnabledStatus"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "FeatureType"
        }
    ];
    return Feature;
}());
exports.Feature = Feature;
