"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupRule = void 0;
var GroupRule = /** @class */ (function () {
    function GroupRule() {
    }
    GroupRule.getAttributeTypeMap = function () {
        return GroupRule.attributeTypeMap;
    };
    GroupRule.discriminator = undefined;
    GroupRule.attributeTypeMap = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "GroupRuleAction"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "GroupRuleConditions"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GroupRuleStatus"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return GroupRule;
}());
exports.GroupRule = GroupRule;
