"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupRuleAction = void 0;
var GroupRuleAction = /** @class */ (function () {
    function GroupRuleAction() {
    }
    GroupRuleAction.getAttributeTypeMap = function () {
        return GroupRuleAction.attributeTypeMap;
    };
    GroupRuleAction.discriminator = undefined;
    GroupRuleAction.attributeTypeMap = [
        {
            "name": "assignUserToGroups",
            "baseName": "assignUserToGroups",
            "type": "GroupRuleGroupAssignment"
        }
    ];
    return GroupRuleAction;
}());
exports.GroupRuleAction = GroupRuleAction;
