"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HardwareUserFactor = void 0;
var HardwareUserFactor = /** @class */ (function () {
    function HardwareUserFactor() {
    }
    HardwareUserFactor.getAttributeTypeMap = function () {
        return HardwareUserFactor.attributeTypeMap;
    };
    HardwareUserFactor.discriminator = undefined;
    HardwareUserFactor.attributeTypeMap = [
        {
            "name": "profile",
            "baseName": "profile",
            "type": "HardwareUserFactorProfile"
        }
    ];
    return HardwareUserFactor;
}());
exports.HardwareUserFactor = HardwareUserFactor;
