"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HrefObject = void 0;
/**
* Used for links
*/
var HrefObject = /** @class */ (function () {
    function HrefObject() {
    }
    HrefObject.getAttributeTypeMap = function () {
        return HrefObject.attributeTypeMap;
    };
    HrefObject.discriminator = undefined;
    HrefObject.attributeTypeMap = [
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "hints",
            "baseName": "hints",
            "type": "HrefObjectHints"
        }
    ];
    return HrefObject;
}());
exports.HrefObject = HrefObject;
