/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export class IdentityProviderPolicyRuleCondition {
    'idpIds'?: Array<string>;
    'provider'?: IdentityProviderPolicyRuleCondition.ProviderEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idpIds",
            "baseName": "idpIds",
            "type": "Array<string>"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "IdentityProviderPolicyRuleCondition.ProviderEnum"
        }    ];

    static getAttributeTypeMap() {
        return IdentityProviderPolicyRuleCondition.attributeTypeMap;
    }
}

export namespace IdentityProviderPolicyRuleCondition {
    export enum ProviderEnum {
        Any = <any> 'ANY',
        Okta = <any> 'OKTA',
        SpecificIdp = <any> 'SPECIFIC_IDP'
    }
}
