"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentityProviderCredentialsTrust = void 0;
var IdentityProviderCredentialsTrust = /** @class */ (function () {
    function IdentityProviderCredentialsTrust() {
    }
    IdentityProviderCredentialsTrust.getAttributeTypeMap = function () {
        return IdentityProviderCredentialsTrust.attributeTypeMap;
    };
    IdentityProviderCredentialsTrust.discriminator = undefined;
    IdentityProviderCredentialsTrust.attributeTypeMap = [
        {
            "name": "audience",
            "baseName": "audience",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "kid",
            "baseName": "kid",
            "type": "string"
        },
        {
            "name": "revocation",
            "baseName": "revocation",
            "type": "IdentityProviderCredentialsTrust.RevocationEnum"
        },
        {
            "name": "revocationCacheLifetime",
            "baseName": "revocationCacheLifetime",
            "type": "number"
        }
    ];
    return IdentityProviderCredentialsTrust;
}());
exports.IdentityProviderCredentialsTrust = IdentityProviderCredentialsTrust;
(function (IdentityProviderCredentialsTrust) {
    var RevocationEnum;
    (function (RevocationEnum) {
        RevocationEnum[RevocationEnum["Crl"] = 'CRL'] = "Crl";
        RevocationEnum[RevocationEnum["DeltaCrl"] = 'DELTA_CRL'] = "DeltaCrl";
        RevocationEnum[RevocationEnum["Ocsp"] = 'OCSP'] = "Ocsp";
    })(RevocationEnum = IdentityProviderCredentialsTrust.RevocationEnum || (IdentityProviderCredentialsTrust.RevocationEnum = {}));
})(IdentityProviderCredentialsTrust = exports.IdentityProviderCredentialsTrust || (exports.IdentityProviderCredentialsTrust = {}));
exports.IdentityProviderCredentialsTrust = IdentityProviderCredentialsTrust;
