/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdentityProviderPolicy } from './identityProviderPolicy';
import { Protocol } from './protocol';

export class IdentityProvider {
    '_links'?: { [key: string]: object; };
    'created'?: Date;
    'id'?: string;
    'issuerMode'?: IdentityProvider.IssuerModeEnum;
    'lastUpdated'?: Date;
    'name'?: string;
    'policy'?: IdentityProviderPolicy;
    'protocol'?: Protocol;
    'status'?: IdentityProvider.StatusEnum;
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "issuerMode",
            "baseName": "issuerMode",
            "type": "IdentityProvider.IssuerModeEnum"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "IdentityProviderPolicy"
        },
        {
            "name": "protocol",
            "baseName": "protocol",
            "type": "Protocol"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "IdentityProvider.StatusEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IdentityProvider.attributeTypeMap;
    }
}

export namespace IdentityProvider {
    export enum IssuerModeEnum {
        OrgUrl = <any> 'ORG_URL',
        CustomUrlDomain = <any> 'CUSTOM_URL_DOMAIN'
    }
    export enum StatusEnum {
        Active = <any> 'ACTIVE',
        Inactive = <any> 'INACTIVE'
    }
}
