"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentityProviderPolicy = void 0;
var IdentityProviderPolicy = /** @class */ (function () {
    function IdentityProviderPolicy() {
    }
    IdentityProviderPolicy.getAttributeTypeMap = function () {
        return IdentityProviderPolicy.attributeTypeMap;
    };
    IdentityProviderPolicy.discriminator = undefined;
    IdentityProviderPolicy.attributeTypeMap = [
        {
            "name": "accountLink",
            "baseName": "accountLink",
            "type": "PolicyAccountLink"
        },
        {
            "name": "maxClockSkew",
            "baseName": "maxClockSkew",
            "type": "number"
        },
        {
            "name": "provisioning",
            "baseName": "provisioning",
            "type": "Provisioning"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "PolicySubject"
        }
    ];
    return IdentityProviderPolicy;
}());
exports.IdentityProviderPolicy = IdentityProviderPolicy;
