"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentityProviderCredentialsClient = void 0;
var IdentityProviderCredentialsClient = /** @class */ (function () {
    function IdentityProviderCredentialsClient() {
    }
    IdentityProviderCredentialsClient.getAttributeTypeMap = function () {
        return IdentityProviderCredentialsClient.attributeTypeMap;
    };
    IdentityProviderCredentialsClient.discriminator = undefined;
    IdentityProviderCredentialsClient.attributeTypeMap = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "clientSecret",
            "baseName": "client_secret",
            "type": "string"
        }
    ];
    return IdentityProviderCredentialsClient;
}());
exports.IdentityProviderCredentialsClient = IdentityProviderCredentialsClient;
