/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineHookChannelConfig } from './inlineHookChannelConfig';

export class InlineHookChannel {
    'config'?: InlineHookChannelConfig;
    'type'?: InlineHookChannel.TypeEnum;
    'version'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "InlineHookChannelConfig"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "InlineHookChannel.TypeEnum"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineHookChannel.attributeTypeMap;
    }
}

export namespace InlineHookChannel {
    export enum TypeEnum {
        Http = <any> 'HTTP'
    }
}
