"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineHookChannelConfigHeaders = void 0;
var InlineHookChannelConfigHeaders = /** @class */ (function () {
    function InlineHookChannelConfigHeaders() {
    }
    InlineHookChannelConfigHeaders.getAttributeTypeMap = function () {
        return InlineHookChannelConfigHeaders.attributeTypeMap;
    };
    InlineHookChannelConfigHeaders.discriminator = undefined;
    InlineHookChannelConfigHeaders.attributeTypeMap = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return InlineHookChannelConfigHeaders;
}());
exports.InlineHookChannelConfigHeaders = InlineHookChannelConfigHeaders;
