"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineHookResponse = void 0;
var InlineHookResponse = /** @class */ (function () {
    function InlineHookResponse() {
    }
    InlineHookResponse.getAttributeTypeMap = function () {
        return InlineHookResponse.attributeTypeMap;
    };
    InlineHookResponse.discriminator = undefined;
    InlineHookResponse.attributeTypeMap = [
        {
            "name": "commands",
            "baseName": "commands",
            "type": "Array<InlineHookResponseCommands>"
        }
    ];
    return InlineHookResponse;
}());
exports.InlineHookResponse = InlineHookResponse;
