/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export enum InlineHookType {
    Oauth2TokensTransform = <any> 'com.okta.oauth2.tokens.transform',
    ImportTransform = <any> 'com.okta.import.transform',
    SamlTokensTransform = <any> 'com.okta.saml.tokens.transform',
    UserPreRegistration = <any> 'com.okta.user.pre-registration',
    UserCredentialPasswordImport = <any> 'com.okta.user.credential.password.import'
}
