/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IonField } from './ionField';

export class IonForm {
    'accepts'?: string;
    'href'?: string;
    'method'?: string;
    'name'?: string;
    'produces'?: string;
    'refresh'?: number;
    'rel'?: Array<string>;
    'relatesTo'?: Array<string>;
    'value'?: Array<IonField>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accepts",
            "baseName": "accepts",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "produces",
            "baseName": "produces",
            "type": "string"
        },
        {
            "name": "refresh",
            "baseName": "refresh",
            "type": "number"
        },
        {
            "name": "rel",
            "baseName": "rel",
            "type": "Array<string>"
        },
        {
            "name": "relatesTo",
            "baseName": "relatesTo",
            "type": "Array<string>"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<IonField>"
        }    ];

    static getAttributeTypeMap() {
        return IonForm.attributeTypeMap;
    }
}

