"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IonForm = void 0;
var IonForm = /** @class */ (function () {
    function IonForm() {
    }
    IonForm.getAttributeTypeMap = function () {
        return IonForm.attributeTypeMap;
    };
    IonForm.discriminator = undefined;
    IonForm.attributeTypeMap = [
        {
            "name": "accepts",
            "baseName": "accepts",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "produces",
            "baseName": "produces",
            "type": "string"
        },
        {
            "name": "refresh",
            "baseName": "refresh",
            "type": "number"
        },
        {
            "name": "rel",
            "baseName": "rel",
            "type": "Array<string>"
        },
        {
            "name": "relatesTo",
            "baseName": "relatesTo",
            "type": "Array<string>"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<IonField>"
        }
    ];
    return IonForm;
}());
exports.IonForm = IonForm;
