/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class JsonWebKey {
    '_links'?: { [key: string]: object; };
    'alg'?: string;
    'created'?: Date;
    'e'?: string;
    'expiresAt'?: Date;
    'key_ops'?: Array<string>;
    'kid'?: string;
    'kty'?: string;
    'lastUpdated'?: Date;
    'n'?: string;
    'status'?: string;
    'use'?: string;
    'x5c'?: Array<string>;
    'x5t'?: string;
    'x5t#S256'?: string;
    'x5u'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "alg",
            "baseName": "alg",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "e",
            "baseName": "e",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "keyOps",
            "baseName": "key_ops",
            "type": "Array<string>"
        },
        {
            "name": "kid",
            "baseName": "kid",
            "type": "string"
        },
        {
            "name": "kty",
            "baseName": "kty",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "n",
            "baseName": "n",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "use",
            "baseName": "use",
            "type": "string"
        },
        {
            "name": "x5c",
            "baseName": "x5c",
            "type": "Array<string>"
        },
        {
            "name": "x5t",
            "baseName": "x5t",
            "type": "string"
        },
        {
            "name": "x5tS256",
            "baseName": "x5t#S256",
            "type": "string"
        },
        {
            "name": "x5u",
            "baseName": "x5u",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return JsonWebKey.attributeTypeMap;
    }
}

