"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JwkUse = void 0;
var JwkUse = /** @class */ (function () {
    function JwkUse() {
    }
    JwkUse.getAttributeTypeMap = function () {
        return JwkUse.attributeTypeMap;
    };
    JwkUse.discriminator = undefined;
    JwkUse.attributeTypeMap = [
        {
            "name": "use",
            "baseName": "use",
            "type": "JwkUse.UseEnum"
        }
    ];
    return JwkUse;
}());
exports.JwkUse = JwkUse;
(function (JwkUse) {
    var UseEnum;
    (function (UseEnum) {
        UseEnum[UseEnum["Sig"] = 'sig'] = "Sig";
    })(UseEnum = JwkUse.UseEnum || (JwkUse.UseEnum = {}));
})(JwkUse = exports.JwkUse || (exports.JwkUse = {}));
exports.JwkUse = JwkUse;
