"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LifecycleExpirationPolicyRuleCondition = void 0;
var LifecycleExpirationPolicyRuleCondition = /** @class */ (function () {
    function LifecycleExpirationPolicyRuleCondition() {
    }
    LifecycleExpirationPolicyRuleCondition.getAttributeTypeMap = function () {
        return LifecycleExpirationPolicyRuleCondition.attributeTypeMap;
    };
    LifecycleExpirationPolicyRuleCondition.discriminator = undefined;
    LifecycleExpirationPolicyRuleCondition.attributeTypeMap = [
        {
            "name": "lifecycleStatus",
            "baseName": "lifecycleStatus",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }
    ];
    return LifecycleExpirationPolicyRuleCondition;
}());
exports.LifecycleExpirationPolicyRuleCondition = LifecycleExpirationPolicyRuleCondition;
