"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinkedObject = void 0;
var LinkedObject = /** @class */ (function () {
    function LinkedObject() {
    }
    LinkedObject.getAttributeTypeMap = function () {
        return LinkedObject.attributeTypeMap;
    };
    LinkedObject.discriminator = undefined;
    LinkedObject.attributeTypeMap = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "associated",
            "baseName": "associated",
            "type": "LinkedObjectDetails"
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "LinkedObjectDetails"
        }
    ];
    return LinkedObject;
}());
exports.LinkedObject = LinkedObject;
