"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogAuthenticationProvider = void 0;
var LogAuthenticationProvider;
(function (LogAuthenticationProvider) {
    LogAuthenticationProvider[LogAuthenticationProvider["OktaAuthenticationProvider"] = 'OKTA_AUTHENTICATION_PROVIDER'] = "OktaAuthenticationProvider";
    LogAuthenticationProvider[LogAuthenticationProvider["ActiveDirectory"] = 'ACTIVE_DIRECTORY'] = "ActiveDirectory";
    LogAuthenticationProvider[LogAuthenticationProvider["Ldap"] = 'LDAP'] = "Ldap";
    LogAuthenticationProvider[LogAuthenticationProvider["Federation"] = 'FEDERATION'] = "Federation";
    LogAuthenticationProvider[LogAuthenticationProvider["Social"] = 'SOCIAL'] = "Social";
    LogAuthenticationProvider[LogAuthenticationProvider["FactorProvider"] = 'FACTOR_PROVIDER'] = "FactorProvider";
})(LogAuthenticationProvider = exports.LogAuthenticationProvider || (exports.LogAuthenticationProvider = {}));
