"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogCredentialProvider = void 0;
var LogCredentialProvider;
(function (LogCredentialProvider) {
    LogCredentialProvider[LogCredentialProvider["OktaAuthenticationProvider"] = 'OKTA_AUTHENTICATION_PROVIDER'] = "OktaAuthenticationProvider";
    LogCredentialProvider[LogCredentialProvider["OktaCredentialProvider"] = 'OKTA_CREDENTIAL_PROVIDER'] = "OktaCredentialProvider";
    LogCredentialProvider[LogCredentialProvider["Rsa"] = 'RSA'] = "Rsa";
    LogCredentialProvider[LogCredentialProvider["Symantec"] = 'SYMANTEC'] = "Symantec";
    LogCredentialProvider[LogCredentialProvider["Google"] = 'GOOGLE'] = "Google";
    LogCredentialProvider[LogCredentialProvider["Duo"] = 'DUO'] = "Duo";
    LogCredentialProvider[LogCredentialProvider["Yubikey"] = 'YUBIKEY'] = "Yubikey";
})(LogCredentialProvider = exports.LogCredentialProvider || (exports.LogCredentialProvider = {}));
