/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum LogCredentialType {
    Otp = <any> 'OTP',
    Sms = <any> 'SMS',
    Password = <any> 'PASSWORD',
    Assertion = <any> 'ASSERTION',
    Iwa = <any> 'IWA',
    Email = <any> 'EMAIL',
    Oauth2 = <any> 'OAUTH2',
    Jwt = <any> 'JWT'
}
