"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogGeographicalContext = void 0;
var LogGeographicalContext = /** @class */ (function () {
    function LogGeographicalContext() {
    }
    LogGeographicalContext.getAttributeTypeMap = function () {
        return LogGeographicalContext.attributeTypeMap;
    };
    LogGeographicalContext.discriminator = undefined;
    LogGeographicalContext.attributeTypeMap = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "geolocation",
            "baseName": "geolocation",
            "type": "LogGeolocation"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        }
    ];
    return LogGeographicalContext;
}());
exports.LogGeographicalContext = LogGeographicalContext;
