"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogIssuer = void 0;
var LogIssuer = /** @class */ (function () {
    function LogIssuer() {
    }
    LogIssuer.getAttributeTypeMap = function () {
        return LogIssuer.attributeTypeMap;
    };
    LogIssuer.discriminator = undefined;
    LogIssuer.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return LogIssuer;
}());
exports.LogIssuer = LogIssuer;
