"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogIpAddress = void 0;
var LogIpAddress = /** @class */ (function () {
    function LogIpAddress() {
    }
    LogIpAddress.getAttributeTypeMap = function () {
        return LogIpAddress.attributeTypeMap;
    };
    LogIpAddress.discriminator = undefined;
    LogIpAddress.attributeTypeMap = [
        {
            "name": "geographicalContext",
            "baseName": "geographicalContext",
            "type": "LogGeographicalContext"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        }
    ];
    return LogIpAddress;
}());
exports.LogIpAddress = LogIpAddress;
