"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogSeverity = void 0;
var LogSeverity;
(function (LogSeverity) {
    LogSeverity[LogSeverity["Debug"] = 'DEBUG'] = "Debug";
    LogSeverity[LogSeverity["Info"] = 'INFO'] = "Info";
    LogSeverity[LogSeverity["Warn"] = 'WARN'] = "Warn";
    LogSeverity[LogSeverity["Error"] = 'ERROR'] = "Error";
})(LogSeverity = exports.LogSeverity || (exports.LogSeverity = {}));
