"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogUserAgent = void 0;
var LogUserAgent = /** @class */ (function () {
    function LogUserAgent() {
    }
    LogUserAgent.getAttributeTypeMap = function () {
        return LogUserAgent.attributeTypeMap;
    };
    LogUserAgent.discriminator = undefined;
    LogUserAgent.attributeTypeMap = [
        {
            "name": "browser",
            "baseName": "browser",
            "type": "string"
        },
        {
            "name": "os",
            "baseName": "os",
            "type": "string"
        },
        {
            "name": "rawUserAgent",
            "baseName": "rawUserAgent",
            "type": "string"
        }
    ];
    return LogUserAgent;
}());
exports.LogUserAgent = LogUserAgent;
