/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MDMEnrollmentPolicyRuleCondition {
    'blockNonSafeAndroid'?: boolean;
    'enrollment'?: MDMEnrollmentPolicyRuleCondition.EnrollmentEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockNonSafeAndroid",
            "baseName": "blockNonSafeAndroid",
            "type": "boolean"
        },
        {
            "name": "enrollment",
            "baseName": "enrollment",
            "type": "MDMEnrollmentPolicyRuleCondition.EnrollmentEnum"
        }    ];

    static getAttributeTypeMap() {
        return MDMEnrollmentPolicyRuleCondition.attributeTypeMap;
    }
}

export namespace MDMEnrollmentPolicyRuleCondition {
    export enum EnrollmentEnum {
        Omm = <any> 'OMM',
        AnyOrNone = <any> 'ANY_OR_NONE'
    }
}
