"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelError = void 0;
var ModelError = /** @class */ (function () {
    function ModelError() {
    }
    ModelError.getAttributeTypeMap = function () {
        return ModelError.attributeTypeMap;
    };
    ModelError.discriminator = undefined;
    ModelError.attributeTypeMap = [
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string"
        },
        {
            "name": "errorSummary",
            "baseName": "errorSummary",
            "type": "string"
        },
        {
            "name": "errorLink",
            "baseName": "errorLink",
            "type": "string"
        },
        {
            "name": "errorId",
            "baseName": "errorId",
            "type": "string"
        },
        {
            "name": "errorCauses",
            "baseName": "errorCauses",
            "type": "Array<ErrorErrorCauses>"
        }
    ];
    return ModelError;
}());
exports.ModelError = ModelError;
