"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OAuth2ScopeConsentGrantSource = void 0;
var OAuth2ScopeConsentGrantSource;
(function (OAuth2ScopeConsentGrantSource) {
    OAuth2ScopeConsentGrantSource[OAuth2ScopeConsentGrantSource["EndUser"] = 'END_USER'] = "EndUser";
    OAuth2ScopeConsentGrantSource[OAuth2ScopeConsentGrantSource["Admin"] = 'ADMIN'] = "Admin";
})(OAuth2ScopeConsentGrantSource = exports.OAuth2ScopeConsentGrantSource || (exports.OAuth2ScopeConsentGrantSource = {}));
