"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OAuthResponseType = void 0;
var OAuthResponseType;
(function (OAuthResponseType) {
    OAuthResponseType[OAuthResponseType["Code"] = 'code'] = "Code";
    OAuthResponseType[OAuthResponseType["Token"] = 'token'] = "Token";
    OAuthResponseType[OAuthResponseType["IdToken"] = 'id_token'] = "IdToken";
})(OAuthResponseType = exports.OAuthResponseType || (exports.OAuthResponseType = {}));
