"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OAuth2Scope = void 0;
var OAuth2Scope = /** @class */ (function () {
    function OAuth2Scope() {
    }
    OAuth2Scope.getAttributeTypeMap = function () {
        return OAuth2Scope.attributeTypeMap;
    };
    OAuth2Scope.discriminator = undefined;
    OAuth2Scope.attributeTypeMap = [
        {
            "name": "consent",
            "baseName": "consent",
            "type": "OAuth2Scope.ConsentEnum"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "metadataPublish",
            "baseName": "metadataPublish",
            "type": "OAuth2Scope.MetadataPublishEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "boolean"
        }
    ];
    return OAuth2Scope;
}());
exports.OAuth2Scope = OAuth2Scope;
(function (OAuth2Scope) {
    var ConsentEnum;
    (function (ConsentEnum) {
        ConsentEnum[ConsentEnum["Required"] = 'REQUIRED'] = "Required";
        ConsentEnum[ConsentEnum["Implicit"] = 'IMPLICIT'] = "Implicit";
        ConsentEnum[ConsentEnum["Admin"] = 'ADMIN'] = "Admin";
    })(ConsentEnum = OAuth2Scope.ConsentEnum || (OAuth2Scope.ConsentEnum = {}));
    var MetadataPublishEnum;
    (function (MetadataPublishEnum) {
        MetadataPublishEnum[MetadataPublishEnum["AllClients"] = 'ALL_CLIENTS'] = "AllClients";
        MetadataPublishEnum[MetadataPublishEnum["NoClients"] = 'NO_CLIENTS'] = "NoClients";
    })(MetadataPublishEnum = OAuth2Scope.MetadataPublishEnum || (OAuth2Scope.MetadataPublishEnum = {}));
})(OAuth2Scope = exports.OAuth2Scope || (exports.OAuth2Scope = {}));
exports.OAuth2Scope = OAuth2Scope;
