/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum OAuthGrantType {
    AuthorizationCode = <any> 'authorization_code',
    Implicit = <any> 'implicit',
    Password = <any> 'password',
    RefreshToken = <any> 'refresh_token',
    ClientCredentials = <any> 'client_credentials'
}
