/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { OAuth2ClaimConditions } from './oAuth2ClaimConditions';

export class OAuth2Claim {
    'links'?: { [key: string]: object; };
    'alwaysIncludeInToken'?: boolean;
    'claimType'?: OAuth2Claim.ClaimTypeEnum;
    'conditions'?: OAuth2ClaimConditions;
    'groupFilterType'?: OAuth2Claim.GroupFilterTypeEnum;
    'id'?: string;
    'name'?: string;
    'status'?: OAuth2Claim.StatusEnum;
    'system'?: boolean;
    'value'?: string;
    'valueType'?: OAuth2Claim.ValueTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "alwaysIncludeInToken",
            "baseName": "alwaysIncludeInToken",
            "type": "boolean"
        },
        {
            "name": "claimType",
            "baseName": "claimType",
            "type": "OAuth2Claim.ClaimTypeEnum"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "OAuth2ClaimConditions"
        },
        {
            "name": "groupFilterType",
            "baseName": "group_filter_type",
            "type": "OAuth2Claim.GroupFilterTypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OAuth2Claim.StatusEnum"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "boolean"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "valueType",
            "baseName": "valueType",
            "type": "OAuth2Claim.ValueTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return OAuth2Claim.attributeTypeMap;
    }
}

export namespace OAuth2Claim {
    export enum ClaimTypeEnum {
        Identity = <any> 'IDENTITY',
        Resource = <any> 'RESOURCE'
    }
    export enum GroupFilterTypeEnum {
        StartsWith = <any> 'STARTS_WITH',
        Equals = <any> 'EQUALS',
        Contains = <any> 'CONTAINS',
        Regex = <any> 'REGEX'
    }
    export enum StatusEnum {
        Active = <any> 'ACTIVE',
        Inactive = <any> 'INACTIVE'
    }
    export enum ValueTypeEnum {
        Expression = <any> 'EXPRESSION',
        Groups = <any> 'GROUPS',
        System = <any> 'SYSTEM'
    }
}
