/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OktaSignOnPolicyRuleActions } from './oktaSignOnPolicyRuleActions';
import { OktaSignOnPolicyRuleConditions } from './oktaSignOnPolicyRuleConditions';

export class OktaSignOnPolicyRule {
    'actions'?: OktaSignOnPolicyRuleActions;
    'conditions'?: OktaSignOnPolicyRuleConditions;
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "OktaSignOnPolicyRuleActions"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "OktaSignOnPolicyRuleConditions"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OktaSignOnPolicyRule.attributeTypeMap;
    }
}

