"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OktaSignOnPolicy = void 0;
var OktaSignOnPolicy = /** @class */ (function () {
    function OktaSignOnPolicy() {
    }
    OktaSignOnPolicy.getAttributeTypeMap = function () {
        return OktaSignOnPolicy.attributeTypeMap;
    };
    OktaSignOnPolicy.discriminator = undefined;
    OktaSignOnPolicy.attributeTypeMap = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "OktaSignOnPolicyConditions"
        }
    ];
    return OktaSignOnPolicy;
}());
exports.OktaSignOnPolicy = OktaSignOnPolicy;
