/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export class OpenIdConnectApplicationIdpInitiatedLogin {
    'mode'?: string;
    'defaultScope'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string"
        },
        {
            "name": "defaultScope",
            "baseName": "default_scope",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return OpenIdConnectApplicationIdpInitiatedLogin.attributeTypeMap;
    }
}

