"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenIdConnectApplication = void 0;
var OpenIdConnectApplication = /** @class */ (function () {
    function OpenIdConnectApplication() {
    }
    OpenIdConnectApplication.getAttributeTypeMap = function () {
        return OpenIdConnectApplication.attributeTypeMap;
    };
    OpenIdConnectApplication.discriminator = undefined;
    OpenIdConnectApplication.attributeTypeMap = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "OAuthApplicationCredentials"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "OpenIdConnectApplicationSettings"
        }
    ];
    return OpenIdConnectApplication;
}());
exports.OpenIdConnectApplication = OpenIdConnectApplication;
