"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenIdConnectApplicationSettings = void 0;
var OpenIdConnectApplicationSettings = /** @class */ (function () {
    function OpenIdConnectApplicationSettings() {
    }
    OpenIdConnectApplicationSettings.getAttributeTypeMap = function () {
        return OpenIdConnectApplicationSettings.attributeTypeMap;
    };
    OpenIdConnectApplicationSettings.discriminator = undefined;
    OpenIdConnectApplicationSettings.attributeTypeMap = [
        {
            "name": "oauthClient",
            "baseName": "oauthClient",
            "type": "OpenIdConnectApplicationSettingsClient"
        }
    ];
    return OpenIdConnectApplicationSettings;
}());
exports.OpenIdConnectApplicationSettings = OpenIdConnectApplicationSettings;
