"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenIdConnectApplicationType = void 0;
var OpenIdConnectApplicationType;
(function (OpenIdConnectApplicationType) {
    OpenIdConnectApplicationType[OpenIdConnectApplicationType["Web"] = 'web'] = "Web";
    OpenIdConnectApplicationType[OpenIdConnectApplicationType["Native"] = 'native'] = "Native";
    OpenIdConnectApplicationType[OpenIdConnectApplicationType["Browser"] = 'browser'] = "Browser";
    OpenIdConnectApplicationType[OpenIdConnectApplicationType["Service"] = 'service'] = "Service";
})(OpenIdConnectApplicationType = exports.OpenIdConnectApplicationType || (exports.OpenIdConnectApplicationType = {}));
