/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { OrgOktaSupportSetting } from './orgOktaSupportSetting';

export class OrgOktaSupportSettingsObj {
    'links'?: { [key: string]: object; };
    'expiration'?: Date;
    'support'?: OrgOktaSupportSetting;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "Date"
        },
        {
            "name": "support",
            "baseName": "support",
            "type": "OrgOktaSupportSetting"
        }    ];

    static getAttributeTypeMap() {
        return OrgOktaSupportSettingsObj.attributeTypeMap;
    }
}

