/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PasswordPolicyAuthenticationProviderCondition {
    'include'?: Array<string>;
    'provider'?: PasswordPolicyAuthenticationProviderCondition.ProviderEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "PasswordPolicyAuthenticationProviderCondition.ProviderEnum"
        }    ];

    static getAttributeTypeMap() {
        return PasswordPolicyAuthenticationProviderCondition.attributeTypeMap;
    }
}

export namespace PasswordPolicyAuthenticationProviderCondition {
    export enum ProviderEnum {
        ActiveDirectory = <any> 'ACTIVE_DIRECTORY',
        Any = <any> 'ANY',
        Ldap = <any> 'LDAP',
        Okta = <any> 'OKTA'
    }
}
