/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PasswordPolicyPasswordSettingsAge } from './passwordPolicyPasswordSettingsAge';
import { PasswordPolicyPasswordSettingsComplexity } from './passwordPolicyPasswordSettingsComplexity';
import { PasswordPolicyPasswordSettingsLockout } from './passwordPolicyPasswordSettingsLockout';

export class PasswordPolicyPasswordSettings {
    'age'?: PasswordPolicyPasswordSettingsAge;
    'complexity'?: PasswordPolicyPasswordSettingsComplexity;
    'lockout'?: PasswordPolicyPasswordSettingsLockout;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "age",
            "baseName": "age",
            "type": "PasswordPolicyPasswordSettingsAge"
        },
        {
            "name": "complexity",
            "baseName": "complexity",
            "type": "PasswordPolicyPasswordSettingsComplexity"
        },
        {
            "name": "lockout",
            "baseName": "lockout",
            "type": "PasswordPolicyPasswordSettingsLockout"
        }    ];

    static getAttributeTypeMap() {
        return PasswordPolicyPasswordSettings.attributeTypeMap;
    }
}

