/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PasswordPolicyPasswordSettingsAge {
    'expireWarnDays'?: number;
    'historyCount'?: number;
    'maxAgeDays'?: number;
    'minAgeMinutes'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expireWarnDays",
            "baseName": "expireWarnDays",
            "type": "number"
        },
        {
            "name": "historyCount",
            "baseName": "historyCount",
            "type": "number"
        },
        {
            "name": "maxAgeDays",
            "baseName": "maxAgeDays",
            "type": "number"
        },
        {
            "name": "minAgeMinutes",
            "baseName": "minAgeMinutes",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PasswordPolicyPasswordSettingsAge.attributeTypeMap;
    }
}

