"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyRecoveryFactorSettings = void 0;
var PasswordPolicyRecoveryFactorSettings = /** @class */ (function () {
    function PasswordPolicyRecoveryFactorSettings() {
    }
    PasswordPolicyRecoveryFactorSettings.getAttributeTypeMap = function () {
        return PasswordPolicyRecoveryFactorSettings.attributeTypeMap;
    };
    PasswordPolicyRecoveryFactorSettings.discriminator = undefined;
    PasswordPolicyRecoveryFactorSettings.attributeTypeMap = [
        {
            "name": "status",
            "baseName": "status",
            "type": "PasswordPolicyRecoveryFactorSettings.StatusEnum"
        }
    ];
    return PasswordPolicyRecoveryFactorSettings;
}());
exports.PasswordPolicyRecoveryFactorSettings = PasswordPolicyRecoveryFactorSettings;
(function (PasswordPolicyRecoveryFactorSettings) {
    var StatusEnum;
    (function (StatusEnum) {
        StatusEnum[StatusEnum["Active"] = 'ACTIVE'] = "Active";
        StatusEnum[StatusEnum["Inactive"] = 'INACTIVE'] = "Inactive";
    })(StatusEnum = PasswordPolicyRecoveryFactorSettings.StatusEnum || (PasswordPolicyRecoveryFactorSettings.StatusEnum = {}));
})(PasswordPolicyRecoveryFactorSettings = exports.PasswordPolicyRecoveryFactorSettings || (exports.PasswordPolicyRecoveryFactorSettings = {}));
exports.PasswordPolicyRecoveryFactorSettings = PasswordPolicyRecoveryFactorSettings;
