"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyRuleActions = void 0;
var PasswordPolicyRuleActions = /** @class */ (function () {
    function PasswordPolicyRuleActions() {
    }
    PasswordPolicyRuleActions.getAttributeTypeMap = function () {
        return PasswordPolicyRuleActions.attributeTypeMap;
    };
    PasswordPolicyRuleActions.discriminator = undefined;
    PasswordPolicyRuleActions.attributeTypeMap = [
        {
            "name": "passwordChange",
            "baseName": "passwordChange",
            "type": "PasswordPolicyRuleAction"
        },
        {
            "name": "selfServicePasswordReset",
            "baseName": "selfServicePasswordReset",
            "type": "PasswordPolicyRuleAction"
        },
        {
            "name": "selfServiceUnlock",
            "baseName": "selfServiceUnlock",
            "type": "PasswordPolicyRuleAction"
        }
    ];
    return PasswordPolicyRuleActions;
}());
exports.PasswordPolicyRuleActions = PasswordPolicyRuleActions;
