"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyRecoveryQuestionProperties = void 0;
var PasswordPolicyRecoveryQuestionProperties = /** @class */ (function () {
    function PasswordPolicyRecoveryQuestionProperties() {
    }
    PasswordPolicyRecoveryQuestionProperties.getAttributeTypeMap = function () {
        return PasswordPolicyRecoveryQuestionProperties.attributeTypeMap;
    };
    PasswordPolicyRecoveryQuestionProperties.discriminator = undefined;
    PasswordPolicyRecoveryQuestionProperties.attributeTypeMap = [
        {
            "name": "complexity",
            "baseName": "complexity",
            "type": "PasswordPolicyRecoveryQuestionComplexity"
        }
    ];
    return PasswordPolicyRecoveryQuestionProperties;
}());
exports.PasswordPolicyRecoveryQuestionProperties = PasswordPolicyRecoveryQuestionProperties;
