"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyDelegationSettings = void 0;
var PasswordPolicyDelegationSettings = /** @class */ (function () {
    function PasswordPolicyDelegationSettings() {
    }
    PasswordPolicyDelegationSettings.getAttributeTypeMap = function () {
        return PasswordPolicyDelegationSettings.attributeTypeMap;
    };
    PasswordPolicyDelegationSettings.discriminator = undefined;
    PasswordPolicyDelegationSettings.attributeTypeMap = [
        {
            "name": "options",
            "baseName": "options",
            "type": "PasswordPolicyDelegationSettingsOptions"
        }
    ];
    return PasswordPolicyDelegationSettings;
}());
exports.PasswordPolicyDelegationSettings = PasswordPolicyDelegationSettings;
