/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { PasswordPolicyRecoveryEmail } from './passwordPolicyRecoveryEmail';
import { PasswordPolicyRecoveryFactorSettings } from './passwordPolicyRecoveryFactorSettings';
import { PasswordPolicyRecoveryQuestion } from './passwordPolicyRecoveryQuestion';

export class PasswordPolicyRecoveryFactors {
    'oktaCall'?: PasswordPolicyRecoveryFactorSettings;
    'oktaEmail'?: PasswordPolicyRecoveryEmail;
    'oktaSms'?: PasswordPolicyRecoveryFactorSettings;
    'recoveryQuestion'?: PasswordPolicyRecoveryQuestion;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "oktaCall",
            "baseName": "okta_call",
            "type": "PasswordPolicyRecoveryFactorSettings"
        },
        {
            "name": "oktaEmail",
            "baseName": "okta_email",
            "type": "PasswordPolicyRecoveryEmail"
        },
        {
            "name": "oktaSms",
            "baseName": "okta_sms",
            "type": "PasswordPolicyRecoveryFactorSettings"
        },
        {
            "name": "recoveryQuestion",
            "baseName": "recovery_question",
            "type": "PasswordPolicyRecoveryQuestion"
        }    ];

    static getAttributeTypeMap() {
        return PasswordPolicyRecoveryFactors.attributeTypeMap;
    }
}

