"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyRecoveryQuestion = void 0;
var PasswordPolicyRecoveryQuestion = /** @class */ (function () {
    function PasswordPolicyRecoveryQuestion() {
    }
    PasswordPolicyRecoveryQuestion.getAttributeTypeMap = function () {
        return PasswordPolicyRecoveryQuestion.attributeTypeMap;
    };
    PasswordPolicyRecoveryQuestion.discriminator = undefined;
    PasswordPolicyRecoveryQuestion.attributeTypeMap = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "PasswordPolicyRecoveryQuestionProperties"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PasswordPolicyRecoveryQuestion.StatusEnum"
        }
    ];
    return PasswordPolicyRecoveryQuestion;
}());
exports.PasswordPolicyRecoveryQuestion = PasswordPolicyRecoveryQuestion;
(function (PasswordPolicyRecoveryQuestion) {
    var StatusEnum;
    (function (StatusEnum) {
        StatusEnum[StatusEnum["Active"] = 'ACTIVE'] = "Active";
        StatusEnum[StatusEnum["Inactive"] = 'INACTIVE'] = "Inactive";
    })(StatusEnum = PasswordPolicyRecoveryQuestion.StatusEnum || (PasswordPolicyRecoveryQuestion.StatusEnum = {}));
})(PasswordPolicyRecoveryQuestion = exports.PasswordPolicyRecoveryQuestion || (exports.PasswordPolicyRecoveryQuestion = {}));
exports.PasswordPolicyRecoveryQuestion = PasswordPolicyRecoveryQuestion;
