"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordPolicyRecoveryFactors = void 0;
var PasswordPolicyRecoveryFactors = /** @class */ (function () {
    function PasswordPolicyRecoveryFactors() {
    }
    PasswordPolicyRecoveryFactors.getAttributeTypeMap = function () {
        return PasswordPolicyRecoveryFactors.attributeTypeMap;
    };
    PasswordPolicyRecoveryFactors.discriminator = undefined;
    PasswordPolicyRecoveryFactors.attributeTypeMap = [
        {
            "name": "oktaCall",
            "baseName": "okta_call",
            "type": "PasswordPolicyRecoveryFactorSettings"
        },
        {
            "name": "oktaEmail",
            "baseName": "okta_email",
            "type": "PasswordPolicyRecoveryEmail"
        },
        {
            "name": "oktaSms",
            "baseName": "okta_sms",
            "type": "PasswordPolicyRecoveryFactorSettings"
        },
        {
            "name": "recoveryQuestion",
            "baseName": "recovery_question",
            "type": "PasswordPolicyRecoveryQuestion"
        }
    ];
    return PasswordPolicyRecoveryFactors;
}());
exports.PasswordPolicyRecoveryFactors = PasswordPolicyRecoveryFactors;
