/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { PlatformConditionEvaluatorPlatformOperatingSystemVersion } from './platformConditionEvaluatorPlatformOperatingSystemVersion';

export class PlatformConditionEvaluatorPlatformOperatingSystem {
    'expression'?: string;
    'type'?: PlatformConditionEvaluatorPlatformOperatingSystem.TypeEnum;
    'version'?: PlatformConditionEvaluatorPlatformOperatingSystemVersion;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expression",
            "baseName": "expression",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PlatformConditionEvaluatorPlatformOperatingSystem.TypeEnum"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "PlatformConditionEvaluatorPlatformOperatingSystemVersion"
        }    ];

    static getAttributeTypeMap() {
        return PlatformConditionEvaluatorPlatformOperatingSystem.attributeTypeMap;
    }
}

export namespace PlatformConditionEvaluatorPlatformOperatingSystem {
    export enum TypeEnum {
        Android = <any> 'ANDROID',
        Ios = <any> 'IOS',
        Windows = <any> 'WINDOWS',
        Osx = <any> 'OSX',
        Other = <any> 'OTHER',
        Any = <any> 'ANY'
    }
}
