"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PolicyAccountLinkFilter = void 0;
var PolicyAccountLinkFilter = /** @class */ (function () {
    function PolicyAccountLinkFilter() {
    }
    PolicyAccountLinkFilter.getAttributeTypeMap = function () {
        return PolicyAccountLinkFilter.attributeTypeMap;
    };
    PolicyAccountLinkFilter.discriminator = undefined;
    PolicyAccountLinkFilter.attributeTypeMap = [
        {
            "name": "groups",
            "baseName": "groups",
            "type": "PolicyAccountLinkFilterGroups"
        }
    ];
    return PolicyAccountLinkFilter;
}());
exports.PolicyAccountLinkFilter = PolicyAccountLinkFilter;
