/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { OktaSignOnPolicyRuleSignonActions } from './oktaSignOnPolicyRuleSignonActions';
import { PasswordPolicyRuleAction } from './passwordPolicyRuleAction';
import { PolicyRuleActionsEnroll } from './policyRuleActionsEnroll';

export class PolicyRuleActions {
    'enroll'?: PolicyRuleActionsEnroll;
    'signon'?: OktaSignOnPolicyRuleSignonActions;
    'passwordChange'?: PasswordPolicyRuleAction;
    'selfServicePasswordReset'?: PasswordPolicyRuleAction;
    'selfServiceUnlock'?: PasswordPolicyRuleAction;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enroll",
            "baseName": "enroll",
            "type": "PolicyRuleActionsEnroll"
        },
        {
            "name": "signon",
            "baseName": "signon",
            "type": "OktaSignOnPolicyRuleSignonActions"
        },
        {
            "name": "passwordChange",
            "baseName": "passwordChange",
            "type": "PasswordPolicyRuleAction"
        },
        {
            "name": "selfServicePasswordReset",
            "baseName": "selfServicePasswordReset",
            "type": "PasswordPolicyRuleAction"
        },
        {
            "name": "selfServiceUnlock",
            "baseName": "selfServiceUnlock",
            "type": "PasswordPolicyRuleAction"
        }    ];

    static getAttributeTypeMap() {
        return PolicyRuleActions.attributeTypeMap;
    }
}

