"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PolicySubject = void 0;
var PolicySubject = /** @class */ (function () {
    function PolicySubject() {
    }
    PolicySubject.getAttributeTypeMap = function () {
        return PolicySubject.attributeTypeMap;
    };
    PolicySubject.discriminator = undefined;
    PolicySubject.attributeTypeMap = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "Array<string>"
        },
        {
            "name": "matchAttribute",
            "baseName": "matchAttribute",
            "type": "string"
        },
        {
            "name": "matchType",
            "baseName": "matchType",
            "type": "PolicySubjectMatchType"
        },
        {
            "name": "userNameTemplate",
            "baseName": "userNameTemplate",
            "type": "PolicyUserNameTemplate"
        }
    ];
    return PolicySubject;
}());
exports.PolicySubject = PolicySubject;
