/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PolicyNetworkCondition {
    'connection'?: PolicyNetworkCondition.ConnectionEnum;
    'exclude'?: Array<string>;
    'include'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connection",
            "baseName": "connection",
            "type": "PolicyNetworkCondition.ConnectionEnum"
        },
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Array<string>"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PolicyNetworkCondition.attributeTypeMap;
    }
}

export namespace PolicyNetworkCondition {
    export enum ConnectionEnum {
        Anywhere = <any> 'ANYWHERE',
        Zone = <any> 'ZONE'
    }
}
