/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PolicyRuleConditions } from './policyRuleConditions';
import { PolicyType } from './policyType';

export class Policy {
    '_embedded'?: { [key: string]: object; };
    '_links'?: { [key: string]: object; };
    'conditions'?: PolicyRuleConditions;
    'created'?: Date;
    'description'?: string;
    'id'?: string;
    'lastUpdated'?: Date;
    'name'?: string;
    'priority'?: number;
    'status'?: Policy.StatusEnum;
    'system'?: boolean;
    'type'?: PolicyType;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "embedded",
            "baseName": "_embedded",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "PolicyRuleConditions"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Policy.StatusEnum"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PolicyType"
        }    ];

    static getAttributeTypeMap() {
        return Policy.attributeTypeMap;
    }
}

export namespace Policy {
    export enum StatusEnum {
        Active = <any> 'ACTIVE',
        Inactive = <any> 'INACTIVE'
    }
}
