"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PolicySubjectMatchType = void 0;
var PolicySubjectMatchType;
(function (PolicySubjectMatchType) {
    PolicySubjectMatchType[PolicySubjectMatchType["Username"] = 'USERNAME'] = "Username";
    PolicySubjectMatchType[PolicySubjectMatchType["Email"] = 'EMAIL'] = "Email";
    PolicySubjectMatchType[PolicySubjectMatchType["UsernameOrEmail"] = 'USERNAME_OR_EMAIL'] = "UsernameOrEmail";
    PolicySubjectMatchType[PolicySubjectMatchType["CustomAttribute"] = 'CUSTOM_ATTRIBUTE'] = "CustomAttribute";
})(PolicySubjectMatchType = exports.PolicySubjectMatchType || (exports.PolicySubjectMatchType = {}));
