/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { ProfileMappingProperty } from './profileMappingProperty';
import { ProfileMappingSource } from './profileMappingSource';

export class ProfileMapping {
    'links'?: { [key: string]: object; };
    'id'?: string;
    'properties'?: { [key: string]: ProfileMappingProperty; };
    'source'?: ProfileMappingSource;
    'target'?: ProfileMappingSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: ProfileMappingProperty; }"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ProfileMappingSource"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "ProfileMappingSource"
        }    ];

    static getAttributeTypeMap() {
        return ProfileMapping.attributeTypeMap;
    }
}

