"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileMapping = void 0;
var ProfileMapping = /** @class */ (function () {
    function ProfileMapping() {
    }
    ProfileMapping.getAttributeTypeMap = function () {
        return ProfileMapping.attributeTypeMap;
    };
    ProfileMapping.discriminator = undefined;
    ProfileMapping.attributeTypeMap = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: ProfileMappingProperty; }"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ProfileMappingSource"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "ProfileMappingSource"
        }
    ];
    return ProfileMapping;
}());
exports.ProfileMapping = ProfileMapping;
