"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileMappingSource = void 0;
var ProfileMappingSource = /** @class */ (function () {
    function ProfileMappingSource() {
    }
    ProfileMappingSource.getAttributeTypeMap = function () {
        return ProfileMappingSource.attributeTypeMap;
    };
    ProfileMappingSource.discriminator = undefined;
    ProfileMappingSource.attributeTypeMap = [
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return ProfileMappingSource;
}());
exports.ProfileMappingSource = ProfileMappingSource;
