"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Protocol = void 0;
var Protocol = /** @class */ (function () {
    function Protocol() {
    }
    Protocol.getAttributeTypeMap = function () {
        return Protocol.attributeTypeMap;
    };
    Protocol.discriminator = undefined;
    Protocol.attributeTypeMap = [
        {
            "name": "algorithms",
            "baseName": "algorithms",
            "type": "ProtocolAlgorithms"
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "IdentityProviderCredentials"
        },
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "ProtocolEndpoints"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "ProtocolEndpoint"
        },
        {
            "name": "relayState",
            "baseName": "relayState",
            "type": "ProtocolRelayState"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<string>"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "ProtocolSettings"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Protocol.TypeEnum"
        }
    ];
    return Protocol;
}());
exports.Protocol = Protocol;
(function (Protocol) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Saml2"] = 'SAML2'] = "Saml2";
        TypeEnum[TypeEnum["Oidc"] = 'OIDC'] = "Oidc";
        TypeEnum[TypeEnum["Oauth2"] = 'OAUTH2'] = "Oauth2";
        TypeEnum[TypeEnum["Mtls"] = 'MTLS'] = "Mtls";
    })(TypeEnum = Protocol.TypeEnum || (Protocol.TypeEnum = {}));
})(Protocol = exports.Protocol || (exports.Protocol = {}));
exports.Protocol = Protocol;
