"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProtocolAlgorithmTypeSignature = void 0;
var ProtocolAlgorithmTypeSignature = /** @class */ (function () {
    function ProtocolAlgorithmTypeSignature() {
    }
    ProtocolAlgorithmTypeSignature.getAttributeTypeMap = function () {
        return ProtocolAlgorithmTypeSignature.attributeTypeMap;
    };
    ProtocolAlgorithmTypeSignature.discriminator = undefined;
    ProtocolAlgorithmTypeSignature.attributeTypeMap = [
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "string"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "ProtocolAlgorithmTypeSignature.ScopeEnum"
        }
    ];
    return ProtocolAlgorithmTypeSignature;
}());
exports.ProtocolAlgorithmTypeSignature = ProtocolAlgorithmTypeSignature;
(function (ProtocolAlgorithmTypeSignature) {
    var ScopeEnum;
    (function (ScopeEnum) {
        ScopeEnum[ScopeEnum["Response"] = 'RESPONSE'] = "Response";
        ScopeEnum[ScopeEnum["Token"] = 'TOKEN'] = "Token";
        ScopeEnum[ScopeEnum["Any"] = 'ANY'] = "Any";
        ScopeEnum[ScopeEnum["Request"] = 'REQUEST'] = "Request";
        ScopeEnum[ScopeEnum["None"] = 'NONE'] = "None";
    })(ScopeEnum = ProtocolAlgorithmTypeSignature.ScopeEnum || (ProtocolAlgorithmTypeSignature.ScopeEnum = {}));
})(ProtocolAlgorithmTypeSignature = exports.ProtocolAlgorithmTypeSignature || (exports.ProtocolAlgorithmTypeSignature = {}));
exports.ProtocolAlgorithmTypeSignature = ProtocolAlgorithmTypeSignature;
