/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProvisioningDeprovisionedCondition } from './provisioningDeprovisionedCondition';
import { ProvisioningSuspendedCondition } from './provisioningSuspendedCondition';

export class ProvisioningConditions {
    'deprovisioned'?: ProvisioningDeprovisionedCondition;
    'suspended'?: ProvisioningSuspendedCondition;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deprovisioned",
            "baseName": "deprovisioned",
            "type": "ProvisioningDeprovisionedCondition"
        },
        {
            "name": "suspended",
            "baseName": "suspended",
            "type": "ProvisioningSuspendedCondition"
        }    ];

    static getAttributeTypeMap() {
        return ProvisioningConditions.attributeTypeMap;
    }
}

