"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProvisioningSuspendedCondition = void 0;
var ProvisioningSuspendedCondition = /** @class */ (function () {
    function ProvisioningSuspendedCondition() {
    }
    ProvisioningSuspendedCondition.getAttributeTypeMap = function () {
        return ProvisioningSuspendedCondition.attributeTypeMap;
    };
    ProvisioningSuspendedCondition.discriminator = undefined;
    ProvisioningSuspendedCondition.attributeTypeMap = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ProvisioningSuspendedCondition.ActionEnum"
        }
    ];
    return ProvisioningSuspendedCondition;
}());
exports.ProvisioningSuspendedCondition = ProvisioningSuspendedCondition;
(function (ProvisioningSuspendedCondition) {
    var ActionEnum;
    (function (ActionEnum) {
        ActionEnum[ActionEnum["None"] = 'NONE'] = "None";
        ActionEnum[ActionEnum["Unsuspend"] = 'UNSUSPEND'] = "Unsuspend";
    })(ActionEnum = ProvisioningSuspendedCondition.ActionEnum || (ProvisioningSuspendedCondition.ActionEnum = {}));
})(ProvisioningSuspendedCondition = exports.ProvisioningSuspendedCondition || (exports.ProvisioningSuspendedCondition = {}));
exports.ProvisioningSuspendedCondition = ProvisioningSuspendedCondition;
