"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProvisioningDeprovisionedCondition = void 0;
var ProvisioningDeprovisionedCondition = /** @class */ (function () {
    function ProvisioningDeprovisionedCondition() {
    }
    ProvisioningDeprovisionedCondition.getAttributeTypeMap = function () {
        return ProvisioningDeprovisionedCondition.attributeTypeMap;
    };
    ProvisioningDeprovisionedCondition.discriminator = undefined;
    ProvisioningDeprovisionedCondition.attributeTypeMap = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ProvisioningDeprovisionedCondition.ActionEnum"
        }
    ];
    return ProvisioningDeprovisionedCondition;
}());
exports.ProvisioningDeprovisionedCondition = ProvisioningDeprovisionedCondition;
(function (ProvisioningDeprovisionedCondition) {
    var ActionEnum;
    (function (ActionEnum) {
        ActionEnum[ActionEnum["None"] = 'NONE'] = "None";
        ActionEnum[ActionEnum["Reactivate"] = 'REACTIVATE'] = "Reactivate";
    })(ActionEnum = ProvisioningDeprovisionedCondition.ActionEnum || (ProvisioningDeprovisionedCondition.ActionEnum = {}));
})(ProvisioningDeprovisionedCondition = exports.ProvisioningDeprovisionedCondition || (exports.ProvisioningDeprovisionedCondition = {}));
exports.ProvisioningDeprovisionedCondition = ProvisioningDeprovisionedCondition;
