/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FactorResultType } from './factorResultType';
import { PushUserFactorProfile } from './pushUserFactorProfile';

export class PushUserFactor {
    'expiresAt'?: Date;
    'factorResult'?: FactorResultType;
    'profile'?: PushUserFactorProfile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "factorResult",
            "baseName": "factorResult",
            "type": "FactorResultType"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "PushUserFactorProfile"
        }    ];

    static getAttributeTypeMap() {
        return PushUserFactor.attributeTypeMap;
    }
}

