"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResetPasswordToken = void 0;
var ResetPasswordToken = /** @class */ (function () {
    function ResetPasswordToken() {
    }
    ResetPasswordToken.getAttributeTypeMap = function () {
        return ResetPasswordToken.attributeTypeMap;
    };
    ResetPasswordToken.discriminator = undefined;
    ResetPasswordToken.attributeTypeMap = [
        {
            "name": "resetPasswordUrl",
            "baseName": "resetPasswordUrl",
            "type": "string"
        }
    ];
    return ResetPasswordToken;
}());
exports.ResetPasswordToken = ResetPasswordToken;
