/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RoleAssignmentType } from './roleAssignmentType';
import { RoleStatus } from './roleStatus';
import { RoleType } from './roleType';

export class Role {
    '_embedded'?: { [key: string]: object; };
    '_links'?: { [key: string]: object; };
    'assignmentType'?: RoleAssignmentType;
    'created'?: Date;
    'description'?: string;
    'id'?: string;
    'label'?: string;
    'lastUpdated'?: Date;
    'status'?: RoleStatus;
    'type'?: RoleType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "embedded",
            "baseName": "_embedded",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "assignmentType",
            "baseName": "assignmentType",
            "type": "RoleAssignmentType"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RoleStatus"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RoleType"
        }    ];

    static getAttributeTypeMap() {
        return Role.attributeTypeMap;
    }
}

