/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export enum RoleType {
    SuperAdmin = <any> 'SUPER_ADMIN',
    OrgAdmin = <any> 'ORG_ADMIN',
    AppAdmin = <any> 'APP_ADMIN',
    UserAdmin = <any> 'USER_ADMIN',
    HelpDeskAdmin = <any> 'HELP_DESK_ADMIN',
    ReadOnlyAdmin = <any> 'READ_ONLY_ADMIN',
    MobileAdmin = <any> 'MOBILE_ADMIN',
    ApiAccessManagementAdmin = <any> 'API_ACCESS_MANAGEMENT_ADMIN',
    ReportAdmin = <any> 'REPORT_ADMIN'
}
