"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SamlApplicationSettingsSignOn = void 0;
var SamlApplicationSettingsSignOn = /** @class */ (function () {
    function SamlApplicationSettingsSignOn() {
    }
    SamlApplicationSettingsSignOn.getAttributeTypeMap = function () {
        return SamlApplicationSettingsSignOn.attributeTypeMap;
    };
    SamlApplicationSettingsSignOn.discriminator = undefined;
    SamlApplicationSettingsSignOn.attributeTypeMap = [
        {
            "name": "allowMultipleAcsEndpoints",
            "baseName": "allowMultipleAcsEndpoints",
            "type": "boolean"
        },
        {
            "name": "acsEndpoints",
            "baseName": "acsEndpoints",
            "type": "Array<AcsEndpoint>"
        },
        {
            "name": "assertionSigned",
            "baseName": "assertionSigned",
            "type": "boolean"
        },
        {
            "name": "attributeStatements",
            "baseName": "attributeStatements",
            "type": "Array<SamlAttributeStatement>"
        },
        {
            "name": "audience",
            "baseName": "audience",
            "type": "string"
        },
        {
            "name": "audienceOverride",
            "baseName": "audienceOverride",
            "type": "string"
        },
        {
            "name": "authnContextClassRef",
            "baseName": "authnContextClassRef",
            "type": "string"
        },
        {
            "name": "defaultRelayState",
            "baseName": "defaultRelayState",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "string"
        },
        {
            "name": "destinationOverride",
            "baseName": "destinationOverride",
            "type": "string"
        },
        {
            "name": "digestAlgorithm",
            "baseName": "digestAlgorithm",
            "type": "string"
        },
        {
            "name": "honorForceAuthn",
            "baseName": "honorForceAuthn",
            "type": "boolean"
        },
        {
            "name": "idpIssuer",
            "baseName": "idpIssuer",
            "type": "string"
        },
        {
            "name": "inlineHooks",
            "baseName": "inlineHooks",
            "type": "Array<SignOnInlineHook>"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "recipientOverride",
            "baseName": "recipientOverride",
            "type": "string"
        },
        {
            "name": "requestCompressed",
            "baseName": "requestCompressed",
            "type": "boolean"
        },
        {
            "name": "responseSigned",
            "baseName": "responseSigned",
            "type": "boolean"
        },
        {
            "name": "signatureAlgorithm",
            "baseName": "signatureAlgorithm",
            "type": "string"
        },
        {
            "name": "slo",
            "baseName": "slo",
            "type": "SingleLogout"
        },
        {
            "name": "spIssuer",
            "baseName": "spIssuer",
            "type": "string"
        },
        {
            "name": "ssoAcsUrl",
            "baseName": "ssoAcsUrl",
            "type": "string"
        },
        {
            "name": "ssoAcsUrlOverride",
            "baseName": "ssoAcsUrlOverride",
            "type": "string"
        },
        {
            "name": "spCertificate",
            "baseName": "spCertificate",
            "type": "SpCertificate"
        },
        {
            "name": "subjectNameIdFormat",
            "baseName": "subjectNameIdFormat",
            "type": "string"
        },
        {
            "name": "subjectNameIdTemplate",
            "baseName": "subjectNameIdTemplate",
            "type": "string"
        }
    ];
    return SamlApplicationSettingsSignOn;
}());
exports.SamlApplicationSettingsSignOn = SamlApplicationSettingsSignOn;
