/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { ApplicationCredentialsScheme } from './applicationCredentialsScheme';
import { ApplicationCredentialsSigning } from './applicationCredentialsSigning';
import { PasswordCredential } from './passwordCredential';

export class SchemeApplicationCredentials {
    'password'?: PasswordCredential;
    'revealPassword'?: boolean;
    'scheme'?: ApplicationCredentialsScheme;
    'signing'?: ApplicationCredentialsSigning;
    'userName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "password",
            "baseName": "password",
            "type": "PasswordCredential"
        },
        {
            "name": "revealPassword",
            "baseName": "revealPassword",
            "type": "boolean"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "ApplicationCredentialsScheme"
        },
        {
            "name": "signing",
            "baseName": "signing",
            "type": "ApplicationCredentialsSigning"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SchemeApplicationCredentials.attributeTypeMap;
    }
}

