"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecurePasswordStoreApplication = void 0;
var SecurePasswordStoreApplication = /** @class */ (function () {
    function SecurePasswordStoreApplication() {
    }
    SecurePasswordStoreApplication.getAttributeTypeMap = function () {
        return SecurePasswordStoreApplication.attributeTypeMap;
    };
    SecurePasswordStoreApplication.discriminator = undefined;
    SecurePasswordStoreApplication.attributeTypeMap = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "SchemeApplicationCredentials"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "SecurePasswordStoreApplicationSettings"
        }
    ];
    return SecurePasswordStoreApplication;
}());
exports.SecurePasswordStoreApplication = SecurePasswordStoreApplication;
