/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export enum SessionAuthenticationMethod {
    Pwd = <any> 'pwd',
    Swk = <any> 'swk',
    Hwk = <any> 'hwk',
    Otp = <any> 'otp',
    Sms = <any> 'sms',
    Tel = <any> 'tel',
    Geo = <any> 'geo',
    Fpt = <any> 'fpt',
    Kba = <any> 'kba',
    Mfa = <any> 'mfa'
}
