"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SessionIdentityProvider = void 0;
var SessionIdentityProvider = /** @class */ (function () {
    function SessionIdentityProvider() {
    }
    SessionIdentityProvider.getAttributeTypeMap = function () {
        return SessionIdentityProvider.attributeTypeMap;
    };
    SessionIdentityProvider.discriminator = undefined;
    SessionIdentityProvider.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SessionIdentityProviderType"
        }
    ];
    return SessionIdentityProvider;
}());
exports.SessionIdentityProvider = SessionIdentityProvider;
