"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SingleLogout = void 0;
var SingleLogout = /** @class */ (function () {
    function SingleLogout() {
    }
    SingleLogout.getAttributeTypeMap = function () {
        return SingleLogout.attributeTypeMap;
    };
    SingleLogout.discriminator = undefined;
    SingleLogout.attributeTypeMap = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "logoutUrl",
            "baseName": "logoutUrl",
            "type": "string"
        }
    ];
    return SingleLogout;
}());
exports.SingleLogout = SingleLogout;
