"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SmsTemplate = void 0;
var SmsTemplate = /** @class */ (function () {
    function SmsTemplate() {
    }
    SmsTemplate.getAttributeTypeMap = function () {
        return SmsTemplate.attributeTypeMap;
    };
    SmsTemplate.discriminator = undefined;
    SmsTemplate.attributeTypeMap = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "string"
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "object"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SmsTemplateType"
        }
    ];
    return SmsTemplate;
}());
exports.SmsTemplate = SmsTemplate;
