"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpCertificate = void 0;
var SpCertificate = /** @class */ (function () {
    function SpCertificate() {
    }
    SpCertificate.getAttributeTypeMap = function () {
        return SpCertificate.attributeTypeMap;
    };
    SpCertificate.discriminator = undefined;
    SpCertificate.attributeTypeMap = [
        {
            "name": "x5c",
            "baseName": "x5c",
            "type": "Array<string>"
        }
    ];
    return SpCertificate;
}());
exports.SpCertificate = SpCertificate;
