"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SwaApplicationSettingsApplication = void 0;
var SwaApplicationSettingsApplication = /** @class */ (function () {
    function SwaApplicationSettingsApplication() {
    }
    SwaApplicationSettingsApplication.getAttributeTypeMap = function () {
        return SwaApplicationSettingsApplication.attributeTypeMap;
    };
    SwaApplicationSettingsApplication.discriminator = undefined;
    SwaApplicationSettingsApplication.attributeTypeMap = [
        {
            "name": "buttonField",
            "baseName": "buttonField",
            "type": "string"
        },
        {
            "name": "loginUrlRegex",
            "baseName": "loginUrlRegex",
            "type": "string"
        },
        {
            "name": "passwordField",
            "baseName": "passwordField",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "usernameField",
            "baseName": "usernameField",
            "type": "string"
        }
    ];
    return SwaApplicationSettingsApplication;
}());
exports.SwaApplicationSettingsApplication = SwaApplicationSettingsApplication;
