"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SwaApplicationSettings = void 0;
var SwaApplicationSettings = /** @class */ (function () {
    function SwaApplicationSettings() {
    }
    SwaApplicationSettings.getAttributeTypeMap = function () {
        return SwaApplicationSettings.attributeTypeMap;
    };
    SwaApplicationSettings.discriminator = undefined;
    SwaApplicationSettings.attributeTypeMap = [
        {
            "name": "app",
            "baseName": "app",
            "type": "SwaApplicationSettingsApplication"
        }
    ];
    return SwaApplicationSettings;
}());
exports.SwaApplicationSettings = SwaApplicationSettings;
