/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SwaApplicationSettingsApplication {
    'buttonField'?: string;
    'loginUrlRegex'?: string;
    'passwordField'?: string;
    'url'?: string;
    'usernameField'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buttonField",
            "baseName": "buttonField",
            "type": "string"
        },
        {
            "name": "loginUrlRegex",
            "baseName": "loginUrlRegex",
            "type": "string"
        },
        {
            "name": "passwordField",
            "baseName": "passwordField",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "usernameField",
            "baseName": "usernameField",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SwaApplicationSettingsApplication.attributeTypeMap;
    }
}

