"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SwaThreeFieldApplicationSettingsApplication = void 0;
var SwaThreeFieldApplicationSettingsApplication = /** @class */ (function () {
    function SwaThreeFieldApplicationSettingsApplication() {
    }
    SwaThreeFieldApplicationSettingsApplication.getAttributeTypeMap = function () {
        return SwaThreeFieldApplicationSettingsApplication.attributeTypeMap;
    };
    SwaThreeFieldApplicationSettingsApplication.discriminator = undefined;
    SwaThreeFieldApplicationSettingsApplication.attributeTypeMap = [
        {
            "name": "buttonSelector",
            "baseName": "buttonSelector",
            "type": "string"
        },
        {
            "name": "extraFieldSelector",
            "baseName": "extraFieldSelector",
            "type": "string"
        },
        {
            "name": "extraFieldValue",
            "baseName": "extraFieldValue",
            "type": "string"
        },
        {
            "name": "loginUrlRegex",
            "baseName": "loginUrlRegex",
            "type": "string"
        },
        {
            "name": "passwordSelector",
            "baseName": "passwordSelector",
            "type": "string"
        },
        {
            "name": "targetURL",
            "baseName": "targetURL",
            "type": "string"
        },
        {
            "name": "userNameSelector",
            "baseName": "userNameSelector",
            "type": "string"
        }
    ];
    return SwaThreeFieldApplicationSettingsApplication;
}());
exports.SwaThreeFieldApplicationSettingsApplication = SwaThreeFieldApplicationSettingsApplication;
