"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenUserFactor = void 0;
var TokenUserFactor = /** @class */ (function () {
    function TokenUserFactor() {
    }
    TokenUserFactor.getAttributeTypeMap = function () {
        return TokenUserFactor.attributeTypeMap;
    };
    TokenUserFactor.discriminator = undefined;
    TokenUserFactor.attributeTypeMap = [
        {
            "name": "profile",
            "baseName": "profile",
            "type": "TokenUserFactorProfile"
        }
    ];
    return TokenUserFactor;
}());
exports.TokenUserFactor = TokenUserFactor;
