/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { TokenAuthorizationServerPolicyRuleActionInlineHook } from './tokenAuthorizationServerPolicyRuleActionInlineHook';

export class TokenAuthorizationServerPolicyRuleAction {
    'accessTokenLifetimeMinutes'?: number;
    'refreshTokenLifetimeMinutes'?: number;
    'refreshTokenWindowMinutes'?: number;
    'inlineHook'?: TokenAuthorizationServerPolicyRuleActionInlineHook;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessTokenLifetimeMinutes",
            "baseName": "accessTokenLifetimeMinutes",
            "type": "number"
        },
        {
            "name": "refreshTokenLifetimeMinutes",
            "baseName": "refreshTokenLifetimeMinutes",
            "type": "number"
        },
        {
            "name": "refreshTokenWindowMinutes",
            "baseName": "refreshTokenWindowMinutes",
            "type": "number"
        },
        {
            "name": "inlineHook",
            "baseName": "inlineHook",
            "type": "TokenAuthorizationServerPolicyRuleActionInlineHook"
        }    ];

    static getAttributeTypeMap() {
        return TokenAuthorizationServerPolicyRuleAction.attributeTypeMap;
    }
}

