"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserPolicyRuleCondition = void 0;
var UserPolicyRuleCondition = /** @class */ (function () {
    function UserPolicyRuleCondition() {
    }
    UserPolicyRuleCondition.getAttributeTypeMap = function () {
        return UserPolicyRuleCondition.attributeTypeMap;
    };
    UserPolicyRuleCondition.discriminator = undefined;
    UserPolicyRuleCondition.attributeTypeMap = [
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Array<string>"
        },
        {
            "name": "inactivity",
            "baseName": "inactivity",
            "type": "InactivityPolicyRuleCondition"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        },
        {
            "name": "lifecycleExpiration",
            "baseName": "lifecycleExpiration",
            "type": "LifecycleExpirationPolicyRuleCondition"
        },
        {
            "name": "passwordExpiration",
            "baseName": "passwordExpiration",
            "type": "PasswordExpirationPolicyRuleCondition"
        },
        {
            "name": "userLifecycleAttribute",
            "baseName": "userLifecycleAttribute",
            "type": "UserLifecycleAttributePolicyRuleCondition"
        }
    ];
    return UserPolicyRuleCondition;
}());
exports.UserPolicyRuleCondition = UserPolicyRuleCondition;
