"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserSchemaAttribute = void 0;
var UserSchemaAttribute = /** @class */ (function () {
    function UserSchemaAttribute() {
    }
    UserSchemaAttribute.getAttributeTypeMap = function () {
        return UserSchemaAttribute.attributeTypeMap;
    };
    UserSchemaAttribute.discriminator = undefined;
    UserSchemaAttribute.attributeTypeMap = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UserSchemaAttributeType"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "mutability",
            "baseName": "mutability",
            "type": "string"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "UserSchemaAttributeScope"
        },
        {
            "name": "_enum",
            "baseName": "enum",
            "type": "Array<string>"
        },
        {
            "name": "oneOf",
            "baseName": "oneOf",
            "type": "Array<UserSchemaAttributeEnum>"
        },
        {
            "name": "minLength",
            "baseName": "minLength",
            "type": "number"
        },
        {
            "name": "maxLength",
            "baseName": "maxLength",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<UserSchemaAttributePermission>"
        },
        {
            "name": "master",
            "baseName": "master",
            "type": "UserSchemaAttributeMaster"
        },
        {
            "name": "union",
            "baseName": "union",
            "type": "UserSchemaAttributeUnion"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "UserSchemaAttributeItems"
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string"
        },
        {
            "name": "unique",
            "baseName": "unique",
            "type": "string"
        },
        {
            "name": "externalName",
            "baseName": "externalName",
            "type": "string"
        },
        {
            "name": "externalNamespace",
            "baseName": "externalNamespace",
            "type": "string"
        }
    ];
    return UserSchemaAttribute;
}());
exports.UserSchemaAttribute = UserSchemaAttribute;
