"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserIdentifierConditionEvaluatorPattern = void 0;
var UserIdentifierConditionEvaluatorPattern = /** @class */ (function () {
    function UserIdentifierConditionEvaluatorPattern() {
    }
    UserIdentifierConditionEvaluatorPattern.getAttributeTypeMap = function () {
        return UserIdentifierConditionEvaluatorPattern.attributeTypeMap;
    };
    UserIdentifierConditionEvaluatorPattern.discriminator = undefined;
    UserIdentifierConditionEvaluatorPattern.attributeTypeMap = [
        {
            "name": "matchType",
            "baseName": "matchType",
            "type": "UserIdentifierConditionEvaluatorPattern.MatchTypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return UserIdentifierConditionEvaluatorPattern;
}());
exports.UserIdentifierConditionEvaluatorPattern = UserIdentifierConditionEvaluatorPattern;
(function (UserIdentifierConditionEvaluatorPattern) {
    var MatchTypeEnum;
    (function (MatchTypeEnum) {
        MatchTypeEnum[MatchTypeEnum["Suffix"] = 'SUFFIX'] = "Suffix";
        MatchTypeEnum[MatchTypeEnum["Expression"] = 'EXPRESSION'] = "Expression";
        MatchTypeEnum[MatchTypeEnum["StartsWith"] = 'STARTS_WITH'] = "StartsWith";
        MatchTypeEnum[MatchTypeEnum["Equals"] = 'EQUALS'] = "Equals";
        MatchTypeEnum[MatchTypeEnum["Contains"] = 'CONTAINS'] = "Contains";
    })(MatchTypeEnum = UserIdentifierConditionEvaluatorPattern.MatchTypeEnum || (UserIdentifierConditionEvaluatorPattern.MatchTypeEnum = {}));
})(UserIdentifierConditionEvaluatorPattern = exports.UserIdentifierConditionEvaluatorPattern || (exports.UserIdentifierConditionEvaluatorPattern = {}));
exports.UserIdentifierConditionEvaluatorPattern = UserIdentifierConditionEvaluatorPattern;
