/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { AuthenticationProvider } from './authenticationProvider';
import { PasswordCredential } from './passwordCredential';
import { RecoveryQuestionCredential } from './recoveryQuestionCredential';

export class UserCredentials {
    'password'?: PasswordCredential;
    'provider'?: AuthenticationProvider;
    'recoveryQuestion'?: RecoveryQuestionCredential;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "password",
            "baseName": "password",
            "type": "PasswordCredential"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "AuthenticationProvider"
        },
        {
            "name": "recoveryQuestion",
            "baseName": "recovery_question",
            "type": "RecoveryQuestionCredential"
        }    ];

    static getAttributeTypeMap() {
        return UserCredentials.attributeTypeMap;
    }
}

