/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';
import { UserSchemaAttributeEnum } from './userSchemaAttributeEnum';

export class UserSchemaAttributeItems {
    '_enum'?: Array<string>;
    'oneOf'?: Array<UserSchemaAttributeEnum>;
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_enum",
            "baseName": "enum",
            "type": "Array<string>"
        },
        {
            "name": "oneOf",
            "baseName": "oneOf",
            "type": "Array<UserSchemaAttributeEnum>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserSchemaAttributeItems.attributeTypeMap;
    }
}

