/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '.';

export class UserIdentifierConditionEvaluatorPattern {
    'matchType'?: UserIdentifierConditionEvaluatorPattern.MatchTypeEnum;
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "matchType",
            "baseName": "matchType",
            "type": "UserIdentifierConditionEvaluatorPattern.MatchTypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserIdentifierConditionEvaluatorPattern.attributeTypeMap;
    }
}

export namespace UserIdentifierConditionEvaluatorPattern {
    export enum MatchTypeEnum {
        Suffix = <any> 'SUFFIX',
        Expression = <any> 'EXPRESSION',
        StartsWith = <any> 'STARTS_WITH',
        Equals = <any> 'EQUALS',
        Contains = <any> 'CONTAINS'
    }
}
