"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserSchemaPublic = void 0;
var UserSchemaPublic = /** @class */ (function () {
    function UserSchemaPublic() {
    }
    UserSchemaPublic.getAttributeTypeMap = function () {
        return UserSchemaPublic.attributeTypeMap;
    };
    UserSchemaPublic.discriminator = undefined;
    UserSchemaPublic.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: UserSchemaAttribute; }"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>"
        }
    ];
    return UserSchemaPublic;
}());
exports.UserSchemaPublic = UserSchemaPublic;
