"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserSchemaAttributeMaster = void 0;
var UserSchemaAttributeMaster = /** @class */ (function () {
    function UserSchemaAttributeMaster() {
    }
    UserSchemaAttributeMaster.getAttributeTypeMap = function () {
        return UserSchemaAttributeMaster.attributeTypeMap;
    };
    UserSchemaAttributeMaster.discriminator = undefined;
    UserSchemaAttributeMaster.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UserSchemaAttributeMasterType"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "Array<UserSchemaAttributeMasterPriority>"
        }
    ];
    return UserSchemaAttributeMaster;
}());
exports.UserSchemaAttributeMaster = UserSchemaAttributeMaster;
