"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserSchemaAttributeItems = void 0;
var UserSchemaAttributeItems = /** @class */ (function () {
    function UserSchemaAttributeItems() {
    }
    UserSchemaAttributeItems.getAttributeTypeMap = function () {
        return UserSchemaAttributeItems.attributeTypeMap;
    };
    UserSchemaAttributeItems.discriminator = undefined;
    UserSchemaAttributeItems.attributeTypeMap = [
        {
            "name": "_enum",
            "baseName": "enum",
            "type": "Array<string>"
        },
        {
            "name": "oneOf",
            "baseName": "oneOf",
            "type": "Array<UserSchemaAttributeEnum>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return UserSchemaAttributeItems;
}());
exports.UserSchemaAttributeItems = UserSchemaAttributeItems;
