/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserIdentifierConditionEvaluatorPattern } from './userIdentifierConditionEvaluatorPattern';

export class UserIdentifierPolicyRuleCondition {
    'attribute'?: string;
    'patterns'?: Array<UserIdentifierConditionEvaluatorPattern>;
    'type'?: UserIdentifierPolicyRuleCondition.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attribute",
            "baseName": "attribute",
            "type": "string"
        },
        {
            "name": "patterns",
            "baseName": "patterns",
            "type": "Array<UserIdentifierConditionEvaluatorPattern>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UserIdentifierPolicyRuleCondition.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return UserIdentifierPolicyRuleCondition.attributeTypeMap;
    }
}

export namespace UserIdentifierPolicyRuleCondition {
    export enum TypeEnum {
        Identifier = <any> 'IDENTIFIER',
        Attribute = <any> 'ATTRIBUTE'
    }
}
