"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VerifyUserFactorResponse = void 0;
var VerifyUserFactorResponse = /** @class */ (function () {
    function VerifyUserFactorResponse() {
    }
    VerifyUserFactorResponse.getAttributeTypeMap = function () {
        return VerifyUserFactorResponse.attributeTypeMap;
    };
    VerifyUserFactorResponse.discriminator = undefined;
    VerifyUserFactorResponse.attributeTypeMap = [
        {
            "name": "embedded",
            "baseName": "_embedded",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "links",
            "baseName": "_links",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "factorResult",
            "baseName": "factorResult",
            "type": "VerifyUserFactorResponse.FactorResultEnum"
        },
        {
            "name": "factorResultMessage",
            "baseName": "factorResultMessage",
            "type": "string"
        }
    ];
    return VerifyUserFactorResponse;
}());
exports.VerifyUserFactorResponse = VerifyUserFactorResponse;
(function (VerifyUserFactorResponse) {
    var FactorResultEnum;
    (function (FactorResultEnum) {
        FactorResultEnum[FactorResultEnum["Success"] = 'SUCCESS'] = "Success";
        FactorResultEnum[FactorResultEnum["Expired"] = 'EXPIRED'] = "Expired";
        FactorResultEnum[FactorResultEnum["Challenge"] = 'CHALLENGE'] = "Challenge";
        FactorResultEnum[FactorResultEnum["Waiting"] = 'WAITING'] = "Waiting";
        FactorResultEnum[FactorResultEnum["Failed"] = 'FAILED'] = "Failed";
        FactorResultEnum[FactorResultEnum["Rejected"] = 'REJECTED'] = "Rejected";
        FactorResultEnum[FactorResultEnum["Timeout"] = 'TIMEOUT'] = "Timeout";
        FactorResultEnum[FactorResultEnum["TimeWindowExceeded"] = 'TIME_WINDOW_EXCEEDED'] = "TimeWindowExceeded";
        FactorResultEnum[FactorResultEnum["PasscodeReplayed"] = 'PASSCODE_REPLAYED'] = "PasscodeReplayed";
        FactorResultEnum[FactorResultEnum["Error"] = 'ERROR'] = "Error";
    })(FactorResultEnum = VerifyUserFactorResponse.FactorResultEnum || (VerifyUserFactorResponse.FactorResultEnum = {}));
})(VerifyUserFactorResponse = exports.VerifyUserFactorResponse || (exports.VerifyUserFactorResponse = {}));
exports.VerifyUserFactorResponse = VerifyUserFactorResponse;
