"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebAuthnUserFactorProfile = void 0;
var WebAuthnUserFactorProfile = /** @class */ (function () {
    function WebAuthnUserFactorProfile() {
    }
    WebAuthnUserFactorProfile.getAttributeTypeMap = function () {
        return WebAuthnUserFactorProfile.attributeTypeMap;
    };
    WebAuthnUserFactorProfile.discriminator = undefined;
    WebAuthnUserFactorProfile.attributeTypeMap = [
        {
            "name": "credentialId",
            "baseName": "credentialId",
            "type": "string"
        },
        {
            "name": "authenticatorName",
            "baseName": "authenticatorName",
            "type": "string"
        }
    ];
    return WebAuthnUserFactorProfile;
}());
exports.WebAuthnUserFactorProfile = WebAuthnUserFactorProfile;
