"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebUserFactorProfile = void 0;
var WebUserFactorProfile = /** @class */ (function () {
    function WebUserFactorProfile() {
    }
    WebUserFactorProfile.getAttributeTypeMap = function () {
        return WebUserFactorProfile.attributeTypeMap;
    };
    WebUserFactorProfile.discriminator = undefined;
    WebUserFactorProfile.attributeTypeMap = [
        {
            "name": "credentialId",
            "baseName": "credentialId",
            "type": "string"
        }
    ];
    return WebUserFactorProfile;
}());
exports.WebUserFactorProfile = WebUserFactorProfile;
