/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WsFederationApplicationSettings } from './wsFederationApplicationSettings';

export class WsFederationApplication {
    'name'?: string;
    'settings'?: WsFederationApplicationSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "WsFederationApplicationSettings"
        }    ];

    static getAttributeTypeMap() {
        return WsFederationApplication.attributeTypeMap;
    }
}

