"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WsFederationApplicationSettingsApplication = void 0;
var WsFederationApplicationSettingsApplication = /** @class */ (function () {
    function WsFederationApplicationSettingsApplication() {
    }
    WsFederationApplicationSettingsApplication.getAttributeTypeMap = function () {
        return WsFederationApplicationSettingsApplication.attributeTypeMap;
    };
    WsFederationApplicationSettingsApplication.discriminator = undefined;
    WsFederationApplicationSettingsApplication.attributeTypeMap = [
        {
            "name": "attributeStatements",
            "baseName": "attributeStatements",
            "type": "string"
        },
        {
            "name": "audienceRestriction",
            "baseName": "audienceRestriction",
            "type": "string"
        },
        {
            "name": "authnContextClassRef",
            "baseName": "authnContextClassRef",
            "type": "string"
        },
        {
            "name": "groupFilter",
            "baseName": "groupFilter",
            "type": "string"
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string"
        },
        {
            "name": "groupValueFormat",
            "baseName": "groupValueFormat",
            "type": "string"
        },
        {
            "name": "nameIDFormat",
            "baseName": "nameIDFormat",
            "type": "string"
        },
        {
            "name": "realm",
            "baseName": "realm",
            "type": "string"
        },
        {
            "name": "siteURL",
            "baseName": "siteURL",
            "type": "string"
        },
        {
            "name": "usernameAttribute",
            "baseName": "usernameAttribute",
            "type": "string"
        },
        {
            "name": "wReplyOverride",
            "baseName": "wReplyOverride",
            "type": "boolean"
        },
        {
            "name": "wReplyURL",
            "baseName": "wReplyURL",
            "type": "string"
        }
    ];
    return WsFederationApplicationSettingsApplication;
}());
exports.WsFederationApplicationSettingsApplication = WsFederationApplicationSettingsApplication;
