"use strict";
/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WsFederationApplication = void 0;
var WsFederationApplication = /** @class */ (function () {
    function WsFederationApplication() {
    }
    WsFederationApplication.getAttributeTypeMap = function () {
        return WsFederationApplication.attributeTypeMap;
    };
    WsFederationApplication.discriminator = undefined;
    WsFederationApplication.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "WsFederationApplicationSettings"
        }
    ];
    return WsFederationApplication;
}());
exports.WsFederationApplication = WsFederationApplication;
